// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{DOUBLE_AUCTION_ELF, DOUBLE_AUCTION_ID};
use risc0_zkvm::{default_prover, ExecutorEnv, InnerReceipt, ProverOpts, recursion::identity_p254};
use risc0_zkvm::seal_to_json;
use serde::{Deserialize, Serialize};
use std::env;
use std::fs;


#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Participant {
    pub id: u32,
    pub role: u32,           // 0 = BUY, 1 = SELL
    pub price: u64,          // bid price for buyers, ask price for sellers  
    pub quantity: u64,       // energy quantity to trade
    pub in_coin: u64,        // initial coin balance
    pub in_energy: u64,      // initial energy balance
    pub out_coin: u64,       // final coin balance (after auction)
    pub out_energy: u64,     // final energy balance (after auction)
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AuctionInput {
    pub participants: Vec<Participant>,
    pub expected_clearing_price: u64,
    pub expected_total_energy_traded: u64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct PublicJournal {
    pub clearing_price: u64, // TODO: remove this field
    pub in_coin: Vec<u64>,
    pub in_energy: Vec<u64>,
    pub out_coin: Vec<u64>,
    pub out_energy: Vec<u64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AuctionResult {
    pub clearing_price: u64,
    pub total_energy_traded: u64,
    pub qualified_buyers: Vec<Participant>,
    pub qualified_sellers: Vec<Participant>,
    pub auction_successful: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AuctionScenario {
    pub scenario_name: String,
    pub description: String,
    pub expected_clearing_price: u64,
    pub expected_total_energy_traded: u64,
    pub participants: Vec<Participant>,
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    println!("\x1b[36mRISC Zero Double Auction System\x1b[0m");
    println!("{}", "═".repeat(50));
    
    // Get scenario file from command line arguments
    let args: Vec<String> = env::args().collect();
    let scenario_file = if args.len() > 1 {
        &args[1]
    } else {
        // Default to sample scenario if no file specified
        "../sample_scenario.json"
    };
    
    // Load scenario from JSON file
    match load_scenario_from_file(scenario_file) {
        Ok(scenario) => {
            println!("\n▸ \x1b[36mScenario Loading\x1b[0m");
            print_tree_item(false, "Scenario name", &scenario.scenario_name, "");
            print_tree_item(false, "Description", &scenario.description, "");
            print_tree_item(true, "Participants", &format!("{} loaded", scenario.participants.len()), "");
            
            // Convert scenario to participants vector
            let participants = scenario.participants.clone();
            
            // Run the auction scenario
            if let Err(e) = run_auction_scenario(&scenario.scenario_name, participants) {
                eprintln!("❌ Auction scenario failed: {}", e);
                std::process::exit(1);
            }
        },
        Err(e) => {
            eprintln!("\x1b[31m✗ Failed to load scenario from {}: {}\x1b[0m", scenario_file, e);
            eprintln!("Provide a valid scenario JSON file (e.g., risc0_example/sample_scenario.json).");
            std::process::exit(1);
        }
    }
}

fn load_scenario_from_file(filename: &str) -> Result<AuctionScenario, Box<dyn std::error::Error>> {
    // Try to read from the specified path
    let content = fs::read_to_string(filename)?;
    let scenario: AuctionScenario = serde_json::from_str(&content)?;
    Ok(scenario)
}


fn run_auction_scenario(_name: &str, mut participants: Vec<Participant>) -> Result<(), Box<dyn std::error::Error>> {
    // Step 1: Display initial state
    println!("\n▸ \x1b[36mInitial Market State\x1b[0m");
    
    let mut buyers = Vec::new();
    let mut sellers = Vec::new();
    
    for p in &participants {
        if p.role == 0 { buyers.push(p); } else { sellers.push(p); }
    }
    
    // Show buyers first
    if !buyers.is_empty() {
        println!("├─ \x1b[32mBuyers\x1b[0m");
        for (i, p) in buyers.iter().enumerate() {
            let is_last_buyer = i == buyers.len() - 1 && sellers.is_empty();
            let prefix = if is_last_buyer { "└─" } else { "├─" };
            println!("│  {} ID{:02} → {} coins/unit, qty: {}, balance: {} coins, {} energy", 
                     prefix, p.id, p.price, p.quantity, p.in_coin, p.in_energy);
        }
    }
    
    // Show sellers
    if !sellers.is_empty() {
        let prefix = if sellers.len() == 1 { "└─" } else { "├─" };
        println!("{} \x1b[33mSellers\x1b[0m", prefix);
        for (i, p) in sellers.iter().enumerate() {
            let is_last = i == sellers.len() - 1;
            let sub_prefix = if is_last { "   └─" } else { "   ├─" };
            println!("{}ID{:02} → {} coins/unit, qty: {}, balance: {} coins, {} energy", 
                     sub_prefix, p.id, p.price, p.quantity, p.in_coin, p.in_energy);
        }
    }
    
    // Step 2: Perform the auction outside the circuit
    let auction_result = perform_double_auction(&mut participants);
    
    // Step 3: Display detailed auction results
    display_auction_results(&auction_result, &participants);
    
    // Step 4: Create input for ZKP verification
    let auction_input = AuctionInput {
        participants: participants.clone(),
        expected_clearing_price: auction_result.clearing_price,
        expected_total_energy_traded: auction_result.total_energy_traded,
    };
    
    // Step 4: Run ZKP verification 
    println!("\n▸ \x1b[36mZKP Generation\x1b[0m");
    
    let env = ExecutorEnv::builder()
        .write(&auction_input)
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();
    let succinct_opts = ProverOpts::succinct();
    
    print_tree_item(false, "RISC Zero proof generation", "STARTED", "");
    let prove_info = prover
        .prove_with_opts(env, DOUBLE_AUCTION_ELF, &succinct_opts)
        .unwrap();

    let receipt = prove_info.receipt;
    let pj: PublicJournal = receipt.journal.decode().unwrap();
    
    // Verify the receipt
    receipt.verify(DOUBLE_AUCTION_ID).unwrap();
    print_tree_item(false, "Public journal validation", &format!("Clearing price: {}, Arrays: {}", pj.clearing_price, pj.in_coin.len()), "");
    
    // Extract c0 and c1 from the receipt claim digest
    extract_and_display_c0_c1(&receipt);
    
    // Demonstrate manual claim digest computation from JSON file
    demonstrate_claim_digest_from_json_and_journal(&pj);
    
    // Validate journal binding (mimics what we'll do in gnark circuit)
    validate_journal_binding(&receipt, &pj);
    
    // Save receipt to file for gnark circuit integration
    save_receipt_to_file(&receipt, &pj)?;
    
    // Generate input.json for Groth16 conversion
    match &receipt.inner {
        InnerReceipt::Succinct(succinct_receipt) => {
            match identity_p254(succinct_receipt) {
                Ok(identity_receipt) => {
                    let seal_bytes: Vec<u8> = identity_receipt.seal.iter()
                        .flat_map(|&x| x.to_le_bytes())
                        .collect();
                    
                    match std::fs::File::create("input.json") {
                        Ok(output_file) => {
                            let cursor = std::io::Cursor::new(&seal_bytes);
                            match seal_to_json(cursor, output_file) {
                                Ok(()) => {
                                    print_tree_item(true, "Groth16 input generation", "COMPLETED", 
                                                  &format!("{} bytes", seal_bytes.len()));
                                },
                                Err(e) => {
                                    print_tree_item(true, "Groth16 input generation", "FAILED", &e.to_string());
                                }
                            }
                        },
                        Err(e) => {
                            print_tree_item(true, "Groth16 input generation", "FAILED", &e.to_string());
                        }
                    }
                },
                Err(e) => {
                    print_tree_item(true, "Identity p254 conversion", "FAILED", &e.to_string());
                }
            }
        },
        _ => {
            print_tree_item(true, "Succinct receipt", "NOT AVAILABLE", "");
        }
    }
    
    println!();
    Ok(())
}

fn perform_double_auction(participants: &mut [Participant]) -> AuctionResult {
    // Create cloned vectors for sorting and analysis (avoids borrowing issues)
    let mut buyers: Vec<Participant> = participants
        .iter()
        .filter(|p| p.role == 0) // BUY
        .cloned()
        .collect();
        
    let mut sellers: Vec<Participant> = participants
        .iter()
        .filter(|p| p.role == 1) // SELL
        .cloned()
        .collect();
    
    // Sort buyers (descending by price) and sellers (ascending by price)
    buyers.sort_by(|a, b| {
        match b.price.cmp(&a.price) {
            std::cmp::Ordering::Equal => a.id.cmp(&b.id),
            other => other,
        }
    }); // Desc by price, tie-break by id asc
    sellers.sort_by(|a, b| {
        match a.price.cmp(&b.price) {
            std::cmp::Ordering::Equal => a.id.cmp(&b.id),
            other => other,
        }
    }); // Asc by price, tie-break by id asc
    
    // Create references for clearing rule
    let buyer_refs: Vec<&Participant> = buyers.iter().collect();
    let seller_refs: Vec<&Participant> = sellers.iter().collect();

    // Uniform marginal-crossing clearing
    let pstar_opt = find_uniform_clearing_host(&buyer_refs, &seller_refs);
    
    if pstar_opt.is_none() {
        // No intersection - no trading occurs, balances remain unchanged
        for participant in participants.iter_mut() {
            participant.out_coin = participant.in_coin;
            participant.out_energy = participant.in_energy;
        }
        return AuctionResult {
            clearing_price: 0,
            total_energy_traded: 0,
            qualified_buyers: Vec::new(),
            qualified_sellers: Vec::new(),
            auction_successful: false,
        };
    }
    
    let (p_star, b_marg, a_marg) = pstar_opt.unwrap();
    let clearing_price = (b_marg + a_marg) / 2; // average

    // Guard against zero clearing price to avoid division by zero
    if clearing_price == 0 {
        for participant in participants.iter_mut() {
            participant.out_coin = participant.in_coin;
            participant.out_energy = participant.in_energy;
        }
        return AuctionResult {
            clearing_price: 0,
            total_energy_traded: 0,
            qualified_buyers: Vec::new(),
            qualified_sellers: Vec::new(),
            auction_successful: false,
        };
    }

    // Determine qualified sets at p_star (NOT at p_c)
    let qualified_buyers: Vec<&Participant> = buyer_refs
        .iter()
        .copied()
        .filter(|b| b.price >= p_star)
        .collect();
    let qualified_sellers: Vec<&Participant> = seller_refs
        .iter()
        .copied()
        .filter(|s| s.price <= p_star)
        .collect();
    
    // Compute total demand and supply at p_star
    let _total_demand: u64 = qualified_buyers.iter().map(|b| b.quantity).sum();
    let _total_supply: u64 = qualified_sellers.iter().map(|s| s.quantity).sum();

    // Build allocation maps: id -> allocated energy
    use std::collections::HashMap;
    let mut alloc_by_id: HashMap<u32, u64> = HashMap::new();

    // Effective demand/supply with budget/stock caps at price p_c
    let mut eff_demand: u64 = 0;
    for b in &qualified_buyers {
        let max_afford = b.in_coin / clearing_price; // floor division
        let cap = if b.quantity < max_afford { b.quantity } else { max_afford };
        eff_demand = eff_demand.saturating_add(cap);
    }
    let mut eff_supply: u64 = 0;
    for s in &qualified_sellers {
        let cap = if s.quantity < s.in_energy { s.quantity } else { s.in_energy };
        eff_supply = eff_supply.saturating_add(cap);
    }
    let traded_total = eff_demand.min(eff_supply);

    if traded_total == 0 {
        for p in participants.iter_mut() {
            p.out_coin = p.in_coin;
            p.out_energy = p.in_energy;
        }
        return AuctionResult {
            clearing_price,
            total_energy_traded: 0,
            qualified_buyers: qualified_buyers.into_iter().cloned().collect(),
            qualified_sellers: qualified_sellers.into_iter().cloned().collect(),
            auction_successful: false,
        };
    }

    if eff_demand >= eff_supply {
        // Supply binding: sellers full (capped by stock); buyers priority by price, capped by budget & qty
        for s in &qualified_sellers {
            let cap = if s.quantity < s.in_energy { s.quantity } else { s.in_energy };
            alloc_by_id.insert(s.id, cap);
        }
        let mut remaining = traded_total;
        for b in &qualified_buyers {
            if remaining == 0 { break; }
            let max_afford = b.in_coin / clearing_price;
            let cap = b.quantity.min(max_afford);
            let take = if cap <= remaining { cap } else { remaining };
            alloc_by_id.insert(b.id, take);
            remaining -= take;
        }
    } else {
        // Demand binding: buyers full (capped by budget & qty); sellers priority by ask, capped by stock
        for b in &qualified_buyers {
            let max_afford = b.in_coin / clearing_price;
            let cap = b.quantity.min(max_afford);
            alloc_by_id.insert(b.id, cap);
        }
        let mut remaining = traded_total;
        for s in &qualified_sellers {
            if remaining == 0 { break; }
            let cap = s.quantity.min(s.in_energy);
            let take = if cap <= remaining { cap } else { remaining };
            alloc_by_id.insert(s.id, take);
            remaining -= take;
        }
    }

    // Update balances according to allocations
    for p in participants.iter_mut() {
        let allocated = *alloc_by_id.get(&p.id).unwrap_or(&0);
        if p.role == 0 { // BUY
            if allocated > 0 {
                p.out_coin = p.in_coin - (clearing_price * allocated);
                p.out_energy = p.in_energy + allocated;
            } else {
                p.out_coin = p.in_coin;
                p.out_energy = p.in_energy;
            }
        } else { // SELL
            if allocated > 0 {
                p.out_coin = p.in_coin + (clearing_price * allocated);
                p.out_energy = p.in_energy - allocated;
            } else {
                p.out_coin = p.in_coin;
                p.out_energy = p.in_energy;
            }
        }
    }

    AuctionResult {
        clearing_price,
        total_energy_traded: traded_total,
        qualified_buyers: qualified_buyers.into_iter().cloned().collect(),
        qualified_sellers: qualified_sellers.into_iter().cloned().collect(),
        auction_successful: clearing_price > 0 && traded_total > 0,
    }
}

fn demand_supply_at_price(buyers: &[&Participant], sellers: &[&Participant], p: u64) -> (u64, u64) {
    let demand: u64 = buyers.iter().filter(|b| b.price >= p).map(|b| b.quantity).sum();
    let supply: u64 = sellers.iter().filter(|s| s.price <= p).map(|s| s.quantity).sum();
    (demand, supply)
}

fn find_uniform_clearing_host(buyers: &[&Participant], sellers: &[&Participant]) -> Option<(u64, u64, u64)> {
    if buyers.is_empty() || sellers.is_empty() {
        return None;
    }

    // Discrete grid of candidate prices
    let mut prices: Vec<u64> = buyers.iter().map(|b| b.price).collect();
    prices.extend(sellers.iter().map(|s| s.price));
    prices.sort();
    prices.dedup();

    // Find p* = smallest p where S(p) >= D(p)
    let mut p_star: Option<u64> = None;
    for &p in &prices {
        let (d, s) = demand_supply_at_price(buyers, sellers, p);
        if s >= d {
            p_star = Some(p);
            break;
        }
    }

    let p_star = match p_star { Some(v) => v, None => return None };

    // Determine marginals at p*
    let mut qualified_buyers: Vec<&Participant> = buyers.iter().copied().filter(|b| b.price >= p_star).collect();
    let mut qualified_sellers: Vec<&Participant> = sellers.iter().copied().filter(|s| s.price <= p_star).collect();
    if qualified_buyers.is_empty() || qualified_sellers.is_empty() { return None; }
    qualified_buyers.sort_by(|a, b| b.price.cmp(&a.price));
    qualified_sellers.sort_by(|a, b| a.price.cmp(&b.price));

    let b_marg = qualified_buyers.last().unwrap().price;
    let a_marg = qualified_sellers.last().unwrap().price;

    Some((p_star, b_marg, a_marg))
}

// Display auction results in a clean, tree-style format matching the Go codebase
fn display_auction_results(auction_result: &AuctionResult, participants: &[Participant]) {
    println!("\n▸ \x1b[36mAuction Results\x1b[0m");
    
    if auction_result.clearing_price > 0 {
        // Print basic auction summary
        print_tree_item(false, "Market Status", "CLEARED", "");
        print_tree_item(false, "Clearing Price", &format!("{} coins/unit", auction_result.clearing_price), "");
        print_tree_item(false, "Volume Traded", &format!("{} energy units", auction_result.total_energy_traded), "");
        print_tree_item(true, "Market Participants", &format!("{} buyers, {} sellers qualified", 
                       auction_result.qualified_buyers.len(), auction_result.qualified_sellers.len()), "");
        
        // Separate buyers and sellers who actually traded
        let mut traded_buyers = Vec::new();
        let mut traded_sellers = Vec::new();
        let mut non_traded = Vec::new();
        
        for p in participants {
            let energy_change = p.out_energy as i64 - p.in_energy as i64;
            if energy_change != 0 {
                if p.role == 0 { // BUY
                    traded_buyers.push(p);
                } else { // SELL
                    traded_sellers.push(p);
                }
            } else {
                non_traded.push(p);
            }
        }
        
        // Display trading summary
        if !traded_buyers.is_empty() || !traded_sellers.is_empty() {
            println!("\n▸ \x1b[36mTrading Summary\x1b[0m");
            
            // Show buyers who traded
            if !traded_buyers.is_empty() {
                println!("├─ \x1b[32mBuyers (Energy Acquired)\x1b[0m");
                for (i, p) in traded_buyers.iter().enumerate() {
                    let energy_acquired = p.out_energy as i64 - p.in_energy as i64;
                    let coins_spent = p.in_coin as i64 - p.out_coin as i64;
                    let is_last_buyer = i == traded_buyers.len() - 1 && traded_sellers.is_empty();
                    let prefix = if is_last_buyer { "└─" } else { "├─" };
                    println!("│  {} ID{:02} → +{} energy, -{} coins @ {} coins/unit", 
                             prefix, p.id, energy_acquired, coins_spent, auction_result.clearing_price);
                }
            }
            
            // Show sellers who traded
            if !traded_sellers.is_empty() {
                let prefix = if traded_sellers.len() == 1 { "└─" } else { "├─" };
                println!("{} \x1b[33mSellers (Energy Sold)\x1b[0m", prefix);
                for (i, p) in traded_sellers.iter().enumerate() {
                    let energy_sold = p.in_energy as i64 - p.out_energy as i64;
                    let coins_earned = p.out_coin as i64 - p.in_coin as i64;
                    let is_last = i == traded_sellers.len() - 1;
                    let sub_prefix = if is_last { "   └─" } else { "   ├─" };
                    println!("{}ID{:02} → -{} energy, +{} coins @ {} coins/unit", 
                             sub_prefix, p.id, energy_sold, coins_earned, auction_result.clearing_price);
                }
            }
        }
        
        // Show non-trading participants
        if !non_traded.is_empty() {
            println!("\n▸ \x1b[90mNon-Trading Participants\x1b[0m");
            for (i, p) in non_traded.iter().enumerate() {
                let role_str = if p.role == 0 { "BUY" } else { "SELL" };
                let reason = if p.role == 0 {
                    if p.price < auction_result.clearing_price {
                        "bid too low"
                    } else {
                        "insufficient funds"
                    }
                } else {
                    if p.price > auction_result.clearing_price {
                        "ask too high"
                    } else {
                        "allocation filled"
                    }
                };
                let is_last = i == non_traded.len() - 1;
                let prefix = if is_last { "└─" } else { "├─" };
                println!("{} ID{:02} ({}) → {} @ {} coins/unit", 
                         prefix, p.id, role_str, reason, p.price);
            }
        }
        
    } else {
        print_tree_item(false, "Market Status", "NO CLEARING", "");
        print_tree_item(true, "Reason", "No price intersection found", "");
    }
    
    // Balance summary
    println!("\n▸ \x1b[36mBalance Summary\x1b[0m");
    let mut _total_coin_flow = 0i64;
    let mut _total_energy_flow = 0i64;
    
    for (i, p) in participants.iter().enumerate() {
        let coin_change = p.out_coin as i64 - p.in_coin as i64;
        let energy_change = p.out_energy as i64 - p.in_energy as i64;
        _total_coin_flow += coin_change.abs();
        _total_energy_flow += energy_change.abs();
        
        let role_str = if p.role == 0 { "BUY" } else { "SELL" };
        let is_last = i == participants.len() - 1;
        let prefix = if is_last { "└─" } else { "├─" };
        
        if coin_change == 0 && energy_change == 0 {
            println!("{} ID{:02} ({:4}) → No change", prefix, p.id, role_str);
        } else {
            println!("{} ID{:02} ({:4}) → {} coins ({:+}), {} energy ({:+})", 
                     prefix, p.id, role_str, p.out_coin, coin_change, p.out_energy, energy_change);
        }
    }
    
    println!();
}

// Helper function to print tree-style items (simplified version of Go's printTreeItem)
fn print_tree_item(is_last: bool, description: &str, status: &str, extra: &str) {
    let prefix = if is_last { "└─" } else { "├─" };
    let desc_formatted = format!("{:<35}", description);
    
    if extra.is_empty() {
        println!("\x1b[90m{}\x1b[0m {} \x1b[32m{}\x1b[0m", prefix, desc_formatted, status);
    } else {
        println!("\x1b[90m{}\x1b[0m {} \x1b[32m{}\x1b[0m \x1b[90m{}\x1b[0m", prefix, desc_formatted, status, extra);
    }
}

// Extract c0 and c1 from RISC Zero receipt using the exact split_digest algorithm
fn extract_and_display_c0_c1(receipt: &risc0_zkvm::Receipt) {
    use risc0_zkvm::sha::Digestible;
    
    println!("\n▸ \x1b[36mc0/c1 Extraction for BitVM/Native Groth16\x1b[0m");
    
    // Get the claim digest from the receipt
    let claim_digest = receipt.claim().expect("Failed to get receipt claim").digest();
    print_tree_item(false, "Receipt claim digest", &format!("0x{}", hex::encode(claim_digest.as_bytes())), "");
    
    // Apply RISC Zero's exact split_digest algorithm
    match split_digest_risc0(claim_digest) {
        Ok((c0, c1)) => {
            let c0_hex = format!("0x{}", hex::encode(fr_to_bytes(&c0)));
            let c1_hex = format!("0x{}", hex::encode(fr_to_bytes(&c1)));
            
            print_tree_item(false, "c0 (first half of claim digest)", &c0_hex, "");
            print_tree_item(true, "c1 (second half of claim digest)", &c1_hex, "");
        },
        Err(e) => {
            print_tree_item(true, "c0/c1 extraction", "FAILED", &e.to_string());
        }
    }
}

// Debug function to try alternative encodings and find the correct one
fn debug_alternative_encodings(receipt: &risc0_zkvm::Receipt) {
    use sha2::{Sha256, Digest as _};
    use risc0_zkvm::sha::Digestible;
    
    let actual_claim_digest = receipt.claim().expect("Failed to get receipt claim").digest();
    let actual_bytes = actual_claim_digest.as_bytes();
    
    if let Ok(maybe_claim) = receipt.claim() {
        if let risc0_zkvm::MaybePruned::Value(claim) = maybe_claim {
            let tag = {
                let mut hasher = Sha256::new();
                hasher.update(b"risc0.ReceiptClaim");
                hasher.finalize()
            };
            
            let input_digest = claim.input.digest();
            let pre_state_digest = claim.pre.digest();
            let post_state_digest = claim.post.digest();
            let output_digest = claim.output.digest();
            
            // Try different combinations
            println!("   Trying different exit code encodings:");
            
            // Try with exit codes shifted by 24 bits (as in Solidity)
            let sys_exit = match &claim.exit_code {
                risc0_zkvm::ExitCode::Halted(code) => *code as u32,
                _ => 0u32,
            };
            
            // Test 1: Shifted exit codes with big-endian
            {
                let mut hasher = Sha256::new();
                hasher.update(&tag);
                hasher.update(input_digest.as_bytes());
                hasher.update(pre_state_digest.as_bytes());
                hasher.update(post_state_digest.as_bytes());
                hasher.update(output_digest.as_bytes());
                hasher.update(&(sys_exit << 24).to_be_bytes());
                hasher.update(&(0u32 << 24).to_be_bytes());
                hasher.update(&4u32.to_be_bytes());
                let result = hasher.finalize();
                if result.as_slice() == actual_bytes {
                    println!("   ✓ MATCH: Shifted << 24, big-endian");
                }
            }
            
            // Test 2: No shift, big-endian  
            {
                let mut hasher = Sha256::new();
                hasher.update(&tag);
                hasher.update(input_digest.as_bytes());
                hasher.update(pre_state_digest.as_bytes());
                hasher.update(post_state_digest.as_bytes());
                hasher.update(output_digest.as_bytes());
                hasher.update(&sys_exit.to_be_bytes());
                hasher.update(&0u32.to_be_bytes());
                hasher.update(&4u32.to_be_bytes());
                let result = hasher.finalize();
                if result.as_slice() == actual_bytes {
                    println!("   ✓ MATCH: No shift, big-endian");
                }
            }
            
            // Test 3: No len field
            {
                let mut hasher = Sha256::new();
                hasher.update(&tag);
                hasher.update(input_digest.as_bytes());
                hasher.update(pre_state_digest.as_bytes());
                hasher.update(post_state_digest.as_bytes());
                hasher.update(output_digest.as_bytes());
                hasher.update(&sys_exit.to_le_bytes());
                hasher.update(&0u32.to_le_bytes());
                // No length field
                let result = hasher.finalize();
                if result.as_slice() == actual_bytes {
                    println!("   ✓ MATCH: No shift, little-endian, no len field");
                }
            }
        }
    }
}

// Compute claim digest from raw values using standard sha2 crate instead of RISC Zero's
fn compute_claim_digest_from_raw_values(
    // Pre-execution state
    pre_pc: u32,
    pre_merkle_root: [u8; 32],
    
    // Post-execution state  
    post_pc: u32,
    post_merkle_root: [u8; 32],
    
    // Journal and assumptions
    journal_bytes: &[u8],
    assumptions_digest_bytes: [u8; 32],
    
    // Exit codes
    sys_exit: u32,
    user_exit: u32,
) -> risc0_zkvm::sha::Digest {
    use sha2::{Sha256 as Sha256Std, Digest as _};
    
    // Helper function to convert sha2 hash to RISC Zero Digest
    let to_risc0_digest = |hash: sha2::digest::Output<Sha256Std>| -> risc0_zkvm::sha::Digest {
        let bytes = hash.as_slice();
        let mut words = [0u32; 8];
        for i in 0..8 {
            let mut word_bytes = [0u8; 4];
            word_bytes.copy_from_slice(&bytes[i*4..(i+1)*4]);
            words[i] = u32::from_le_bytes(word_bytes);
        }
        risc0_zkvm::sha::Digest::new(words)
    };
    
    // Step 1: Compute the pre_state_digest
    // SystemState digest = tagged_struct("risc0.SystemState", &[merkle_root], &[pc])
    let pre_state_digest = {
        let tag = Sha256Std::digest(b"risc0.SystemState");
        let mut buf = Vec::new();
        buf.extend_from_slice(tag.as_slice());
        buf.extend_from_slice(&pre_merkle_root);
        buf.extend_from_slice(&pre_pc.to_le_bytes());
        let down_count: u16 = 1; // One digest (merkle_root)
        buf.extend_from_slice(&down_count.to_le_bytes());
        to_risc0_digest(Sha256Std::digest(&buf))
    };
    
    // Step 2: Compute the post_state_digest
    let post_state_digest = {
        let tag = Sha256Std::digest(b"risc0.SystemState");
        let mut buf = Vec::new();
        buf.extend_from_slice(tag.as_slice());
        buf.extend_from_slice(&post_merkle_root);
        buf.extend_from_slice(&post_pc.to_le_bytes());
        let down_count: u16 = 1;
        buf.extend_from_slice(&down_count.to_le_bytes());
        to_risc0_digest(Sha256Std::digest(&buf))
    };
    
    // Step 3: Compute the journal_digest
    let journal_digest = to_risc0_digest(Sha256Std::digest(journal_bytes));
    
    // Step 4: Compute the output_digest
    // Output digest = tagged_struct("risc0.Output", &[journal_digest, assumptions_digest], &[])
    let output_digest = {
        let tag = Sha256Std::digest(b"risc0.Output");
        let mut buf = Vec::new();
        buf.extend_from_slice(tag.as_slice());
        buf.extend_from_slice(journal_digest.as_bytes());
        buf.extend_from_slice(&assumptions_digest_bytes);
        // No data array for Output
        let down_count: u16 = 2; // Two digests (journal, assumptions)
        buf.extend_from_slice(&down_count.to_le_bytes());
        to_risc0_digest(Sha256Std::digest(&buf))
    };
    
    // Step 5: Input digest is always zero for now
    let input_digest = risc0_zkvm::sha::Digest::new([0u32; 8]);
    
    // Step 6: Compute the final claim digest
    // ReceiptClaim digest = tagged_struct("risc0.ReceiptClaim", 
    //                                     &[input, pre, post, output],
    //                                     &[sys_exit, user_exit])
    let claim_digest = {
        let tag = Sha256Std::digest(b"risc0.ReceiptClaim");
        let mut buf = Vec::new();
        buf.extend_from_slice(tag.as_slice());
        buf.extend_from_slice(input_digest.as_bytes());
        buf.extend_from_slice(pre_state_digest.as_bytes());
        buf.extend_from_slice(post_state_digest.as_bytes());
        buf.extend_from_slice(output_digest.as_bytes());
        buf.extend_from_slice(&sys_exit.to_le_bytes());
        buf.extend_from_slice(&user_exit.to_le_bytes());
        let down_count: u16 = 4; // Four digests
        buf.extend_from_slice(&down_count.to_le_bytes());
        to_risc0_digest(Sha256Std::digest(&buf))
    };
    
    println!("\n   [RAW VALUES CLAIM COMPUTATION]:");
    println!("     Pre-state: pc={}, merkle_root=0x{}", pre_pc, hex::encode(&pre_merkle_root));
    println!("     Post-state: pc={}, merkle_root=0x{}", post_pc, hex::encode(&post_merkle_root));
    println!("     Journal: {} bytes, digest=0x{}", journal_bytes.len(), hex::encode(journal_digest.as_bytes()));
    println!("     Assumptions digest: 0x{}", hex::encode(&assumptions_digest_bytes));
    println!("     Exit codes: sys={}, user={}", sys_exit, user_exit);
    println!("\n     Intermediate digests:");
    println!("       input_digest: 0x{}", hex::encode(input_digest.as_bytes()));
    println!("       pre_state_digest: 0x{}", hex::encode(pre_state_digest.as_bytes()));
    println!("       post_state_digest: 0x{}", hex::encode(post_state_digest.as_bytes()));
    println!("       output_digest: 0x{}", hex::encode(output_digest.as_bytes()));
    println!("\n     Final claim_digest: 0x{}", hex::encode(claim_digest.as_bytes()));
    
    claim_digest
}

// Demonstrate claim digest computation from JSON file and raw journal data
fn demonstrate_claim_digest_from_json_and_journal(journal: &PublicJournal) {
    use risc0_zkvm::sha::{Digestible, Sha256};
    use std::fs;
    
    println!("\n▸ \x1b[36mClaim Digest Computation from JSON File and Raw Journal\x1b[0m");
    
    // Read the receipt from JSON file
    let receipt_json_path = "/home/hamza/thesis/PPEM-clean/risc0/risc0_receipt.json";
    let receipt_json_str = fs::read_to_string(receipt_json_path)
        .expect("Failed to read risc0_receipt.json");
    let receipt: risc0_zkvm::Receipt = serde_json::from_str(&receipt_json_str)
        .expect("Failed to parse receipt JSON");
    
    // Get the actual claim digest from the loaded receipt for comparison
    let actual_claim_digest = receipt.claim().expect("Failed to get receipt claim").digest();
    
    // Let's also directly use RISC Zero's into_pair to get the exact values
    if let Ok(maybe_claim) = receipt.claim() {
        if let risc0_zkvm::MaybePruned::Value(claim) = maybe_claim {
            println!("\n   [DEBUG] Raw Receipt Claim:");
            // Use RISC Zero's into_pair() directly
            let (sys, user) = claim.exit_code.into_pair();
            println!("     ExitCode.into_pair() = ({}, {})", sys, user);
            
            // Print the exit code details
            match &claim.exit_code {
                risc0_zkvm::ExitCode::Halted(code) => {
                    println!("     ExitCode::Halted({})", code);
                },
                risc0_zkvm::ExitCode::Paused(code) => {
                    println!("     ExitCode::Paused({})", code);
                },
                risc0_zkvm::ExitCode::SystemSplit => {
                    println!("     ExitCode::SystemSplit");
                },
                _ => {
                    println!("     ExitCode: Unknown variant");
                }
            }
        }
    }
    
    // Test with raw values computation using our own journal serialization
    if let Ok(maybe_claim) = receipt.claim() {
        if let risc0_zkvm::MaybePruned::Value(claim) = maybe_claim {
            println!("\n   [TESTING WITH CUSTOM JOURNAL SERIALIZATION]");
            
            // Extract raw values from the claim
            let (pre_pc, pre_merkle_root) = if let risc0_zkvm::MaybePruned::Value(pre_state) = &claim.pre {
                (pre_state.pc, {
                    let mut bytes = [0u8; 32];
                    bytes.copy_from_slice(pre_state.merkle_root.as_bytes());
                    bytes
                })
            } else {
                println!("   Pre-state is pruned, cannot extract raw values");
                (0, [0u8; 32])
            };
            
            let (post_pc, post_merkle_root) = if let risc0_zkvm::MaybePruned::Value(post_state) = &claim.post {
                (post_state.pc, {
                    let mut bytes = [0u8; 32];
                    bytes.copy_from_slice(post_state.merkle_root.as_bytes());
                    bytes
                })
            } else {
                println!("   Post-state is pruned, cannot extract raw values");
                (0, [0u8; 32])
            };
            
            // Compute journal bytes from PublicJournal directly (not from receipt)
            let journal_bytes = serialize_journal_risc0_format(journal);
            println!("   Computing journal from PublicJournal: {} bytes", journal_bytes.len());
            
            // Assumptions digest (usually zero)
            let assumptions_digest = if let risc0_zkvm::MaybePruned::Value(Some(output)) = &claim.output {
                let mut bytes = [0u8; 32];
                bytes.copy_from_slice(output.assumptions.digest().as_bytes());
                bytes
            } else {
                [0u8; 32] // Zero digest for no assumptions
            };
            
            // Get exit codes
            let (sys_exit, user_exit) = claim.exit_code.into_pair();
            
            // Compute claim digest from raw values with our journal
            let computed_from_raw = compute_claim_digest_from_raw_values(
                pre_pc,
                pre_merkle_root,
                post_pc,
                post_merkle_root,
                &journal_bytes,
                assumptions_digest,
                sys_exit,
                user_exit,
            );
            
            // Compare with RISC Zero's digest
            let matches_raw = computed_from_raw.as_bytes() == actual_claim_digest.as_bytes();
            println!("\n   Custom journal computation matches RISC Zero: {}", 
                     if matches_raw { "✓ YES" } else { "✗ NO" });
            
            if matches_raw {
                println!("\n✅ \x1b[32mSUCCESS! We can compute the exact claim digest with custom journal serialization!\x1b[0m");
            }
        }
    }
    
    // Also try the original method
    match compute_manual_claim_digest(&receipt) {
        Ok(computed_digest) => {
            let matches = computed_digest.as_bytes() == actual_claim_digest.as_bytes();
            
            print_tree_item(false, "Manual computation", "COMPLETED", "");
            print_tree_item(false, "Computed digest", &format!("0x{}", hex::encode(computed_digest.as_bytes())), "");
            print_tree_item(false, "Actual digest", &format!("0x{}", hex::encode(actual_claim_digest.as_bytes())), "");
            print_tree_item(true, "Digests match", if matches { "✓ YES" } else { "✗ NO" }, "");
            
            if matches {
                println!("\n✅ \x1b[32mSuccess! Manual claim digest computation matches RISC Zero's digest()!\x1b[0m");
                println!("   This proves we can compute the claim digest without relying on RISC Zero.");
            } else {
                println!("\n❌ \x1b[31mError: Manual computation doesn't match RISC Zero's digest().\x1b[0m");
                println!("   Need to debug the implementation.");
            }
        },
        Err(e) => {
            print_tree_item(true, "Manual computation", "FAILED", &e.to_string());
        }
    }
}

// Validate journal binding constraint (mimics gnark circuit implementation)
fn validate_journal_binding(receipt: &risc0_zkvm::Receipt, journal: &PublicJournal) {
    use risc0_zkvm::sha::Digestible;
    
    println!("\n▸ \x1b[36mJournal Binding Validation (Gnark Circuit Simulation)\x1b[0m");
    
    // Step 1: Get the actual journal bytes from RISC Zero receipt
    let actual_journal_bytes = &receipt.journal.bytes;
    let actual_journal_digest = {
        use sha2::{Sha256, Digest as _};
        let mut hasher = Sha256::new();
        hasher.update(actual_journal_bytes);
        hasher.finalize().to_vec()
    };
    print_tree_item(false, "Actual journal bytes digest", &format!("0x{}", hex::encode(&actual_journal_digest)), "");
    
    // Step 2: Extract RISC Zero journal digest from receipt
    let risc0_journal_digest = receipt.journal.digest();
    print_tree_item(false, "RISC Zero journal digest", &format!("0x{}", hex::encode(risc0_journal_digest.as_bytes())), "");
    
    // Step 3: Compute circuit-side journal digest (what we'll do in gnark)
    let circuit_journal_digest = compute_circuit_journal_digest(journal);
    print_tree_item(false, "Circuit computed journal digest", &format!("0x{}", hex::encode(&circuit_journal_digest)), "");
    
    // Step 4: Compute claim digest using our computed journal digest and receipt data
    let computed_claim_digest = match compute_claim_digest_from_receipt_and_journal_digest(receipt, &circuit_journal_digest) {
        Ok(digest) => digest,
        Err(e) => {
            print_tree_item(false, "Computed claim digest", "FAILED", &e.to_string());
            return;
        }
    };
    
    // Get the actual claim digest from receipt
    let actual_claim_digest = receipt.claim().expect("Failed to get receipt claim").digest();
    
    print_tree_item(false, "Computed claim digest", &format!("0x{}", hex::encode(computed_claim_digest.as_bytes())), "");
    print_tree_item(false, "Actual claim digest", &format!("0x{}", hex::encode(actual_claim_digest.as_bytes())), "");
    
    // Step 4: Compare all three digests to understand the relationships
    println!("\n   \x1b[93m[DEBUG] Digest Analysis:\x1b[0m");
    println!("   Actual journal bytes digest: 0x{}", hex::encode(&actual_journal_digest));
    println!("   RISC Zero journal digest:    0x{}", hex::encode(risc0_journal_digest.as_bytes()));
    println!("   Circuit computed digest:     0x{}", hex::encode(&circuit_journal_digest));
    println!("   Journal bytes length: {} bytes", actual_journal_bytes.len());
    
    // Export journal data for Python verification
    println!("\n   \x1b[96m[PYTHON DATA] Journal values for verification:\x1b[0m");
    println!("   clearing_price: {}", journal.clearing_price);
    println!("   in_coin: {:?}", journal.in_coin);
    println!("   in_energy: {:?}", journal.in_energy);
    println!("   out_coin: {:?}", journal.out_coin);
    println!("   out_energy: {:?}", journal.out_energy);
    
    // Check which digest matches what
    let actual_matches_risc0 = actual_journal_digest == risc0_journal_digest.as_bytes();
    let circuit_matches_risc0 = circuit_journal_digest == risc0_journal_digest.as_bytes();
    let circuit_matches_actual = circuit_journal_digest == actual_journal_digest;
    let computed_claim_matches_actual = computed_claim_digest.as_bytes() == actual_claim_digest.as_bytes();
    
    print_tree_item(false, "Actual bytes digest == RISC0 digest", if actual_matches_risc0 { "✓ MATCH" } else { "✗ NO MATCH" }, "");
    print_tree_item(false, "Circuit digest == RISC0 digest", if circuit_matches_risc0 { "✓ MATCH" } else { "✗ NO MATCH" }, "");
    print_tree_item(false, "Circuit digest == Actual digest", if circuit_matches_actual { "✓ MATCH" } else { "✗ NO MATCH" }, "");
    print_tree_item(true, "Computed claim == Actual claim", if computed_claim_matches_actual { "✓ MATCH" } else { "✗ NO MATCH" }, "");
    
    // Final binding constraint result
    if circuit_matches_risc0 {
        println!("\n✅ \x1b[32mJournal binding constraint VALID!\x1b[0m");
    } else {
        println!("\n❌ \x1b[31mJournal binding constraint INVALID!\x1b[0m");
        if circuit_matches_actual && !actual_matches_risc0 {
            println!("   \x1b[33m→ RISC Zero uses a different digest than SHA-256 of raw bytes!\x1b[0m");
        }
    }
}

// Compute journal digest exactly as we would in the gnark circuit
fn compute_circuit_journal_digest(journal: &PublicJournal) -> Vec<u8> {
    use sha2::{Sha256, Digest as _};
    
    // Serialize journal in the same format that RISC Zero uses
    // This must match risc0_zkvm's internal serialization exactly
    let serialized = serialize_journal_risc0_format(journal);
    
    // Compute SHA-256 (same as RISC Zero)
    let mut hasher = Sha256::new();
    hasher.update(&serialized);
    hasher.finalize().to_vec()
}

// Create a new function that computes claim digest exactly as RISC Zero does internally
fn compute_manual_claim_digest(receipt: &risc0_zkvm::Receipt) -> Result<risc0_zkvm::sha::Digest, Box<dyn std::error::Error>> {
    use risc0_zkvm::sha::{Digestible, Sha256};
    
    // Get the claim from receipt and extract the actual ReceiptClaim from MaybePruned
    let maybe_claim = receipt.claim()?;
    let claim = match maybe_claim {
        risc0_zkvm::MaybePruned::Value(claim) => claim,
        risc0_zkvm::MaybePruned::Pruned(_) => return Err("Receipt claim is pruned, cannot extract fields".into()),
    };
    
    // RISC Zero's claim digest computation uses the tagged_struct! macro
    // Based on the source code, tagged_struct does:
    // 1. Computes TAG = sha256("risc0.ReceiptClaim")  
    // 2. Hashes: TAG || down[0] || down[1] || ... || data[0] || data[1] || ... || len(down)
    // where down = [input, pre, post, output] digests (4 elements)
    // and data = [sys_exit, user_exit] as u32 values
    
    // TAG = sha256("risc0.ReceiptClaim") using RISC Zero's SHA implementation
    let tag_digest = risc0_zkvm::sha::Impl::hash_bytes(b"risc0.ReceiptClaim");
    
    // Extract claim fields from the actual ReceiptClaim
    let input_digest = claim.input.digest();
    let pre_state_digest = claim.pre.digest(); 
    let post_state_digest = claim.post.digest();
    let output_digest = claim.output.digest();
    
    // Use RISC Zero's own into_pair() method directly
    let (sys_exit, user_exit) = claim.exit_code.into_pair();
    
    // Debug: Print all the components before hashing
    println!("\n   [MANUAL CLAIM DIGEST COMPUTATION]:");
    println!("     tag_digest: 0x{}", hex::encode(tag_digest.as_bytes()));
    println!("     input_digest: 0x{}", hex::encode(input_digest.as_bytes()));
    println!("     pre_state_digest: 0x{}", hex::encode(pre_state_digest.as_bytes()));
    println!("     post_state_digest: 0x{}", hex::encode(post_state_digest.as_bytes()));
    println!("     output_digest: 0x{}", hex::encode(output_digest.as_bytes()));
    println!("     sys_exit: {} (0x{:08x})", sys_exit, sys_exit);
    println!("     user_exit: {} (0x{:08x})", user_exit, user_exit);
    
    // Exactly match RISC Zero's tagged_struct implementation from risc0/binfmt/src/hash.rs
    // Build the byte buffer exactly as RISC Zero does
    let mut all = Vec::<u8>::new();
    
    // 1. Add tag digest
    all.extend_from_slice(tag_digest.as_bytes());
    
    // 2. Add "down" array (4 digests, each 32 bytes) in order
    all.extend_from_slice(input_digest.as_bytes());
    all.extend_from_slice(pre_state_digest.as_bytes());
    all.extend_from_slice(post_state_digest.as_bytes());
    all.extend_from_slice(output_digest.as_bytes());
    
    // 3. Add "data" array (exit codes as u32 values in little-endian)
    all.extend_from_slice(&sys_exit.to_le_bytes());
    all.extend_from_slice(&user_exit.to_le_bytes());
    
    // 4. Add down_count as u16 (not u32!) in little-endian
    let down_count: u16 = 4;
    all.extend_from_slice(&down_count.to_le_bytes());
    
    // Compute the final hash using RISC Zero's SHA implementation
    let result = risc0_zkvm::sha::Impl::hash_bytes(&all);
    Ok(*result)
}

// Keep the old function for backwards compatibility but have it call the new one
fn compute_claim_digest_from_receipt_and_journal_digest(receipt: &risc0_zkvm::Receipt, _journal_digest: &[u8]) -> Result<risc0_zkvm::sha::Digest, Box<dyn std::error::Error>> {
    // Note: We ignore the journal_digest parameter and compute the claim digest directly from the receipt
    // This is because RISC Zero uses the output digest (which includes journal + assumptions), not just the journal digest
    compute_manual_claim_digest(receipt)
}

// Helper function to convert [u8; 32] to [u32; 8] for RISC Zero Digest
fn bytes_to_u32_array(bytes: &[u8]) -> Result<[u32; 8], Box<dyn std::error::Error>> {
    if bytes.len() != 32 {
        return Err(format!("Expected 32 bytes, got {}", bytes.len()).into());
    }
    
    let mut words = [0u32; 8];
    for (i, chunk) in bytes.chunks(4).enumerate() {
        if i < 8 {
            let mut word_bytes = [0u8; 4];
            word_bytes.copy_from_slice(chunk);
            words[i] = u32::from_be_bytes(word_bytes); // RISC Zero uses big-endian for digest words
        }
    }
    Ok(words)
}

// Serialize journal in RISC Zero's exact format (u32-word based)
fn serialize_journal_risc0_format(journal: &PublicJournal) -> Vec<u8> {
    // RISC Zero serializes to u32 words - implement exactly like their serializer
    let mut words: Vec<u32> = Vec::new();
    
    // Serialize clearing_price (u64 -> 2 words)
    let price_bytes = journal.clearing_price.to_le_bytes();
    words.push(u32::from_le_bytes([price_bytes[0], price_bytes[1], price_bytes[2], price_bytes[3]]));
    words.push(u32::from_le_bytes([price_bytes[4], price_bytes[5], price_bytes[6], price_bytes[7]]));
    
    // Serialize Vec<u64> arrays
    serialize_u64_vec_to_words(&mut words, &journal.in_coin);
    serialize_u64_vec_to_words(&mut words, &journal.in_energy);
    serialize_u64_vec_to_words(&mut words, &journal.out_coin);
    serialize_u64_vec_to_words(&mut words, &journal.out_energy);
    
    // Convert u32 words to bytes (little-endian)
    let mut bytes = Vec::new();
    for word in words {
        bytes.extend_from_slice(&word.to_le_bytes());
    }
    bytes
}

// Helper to serialize Vec<u64> to u32 words (RISC Zero format)
fn serialize_u64_vec_to_words(words: &mut Vec<u32>, vec: &[u64]) {
    // Length as u32
    words.push(vec.len() as u32);
    
    // Each u64 as 2 u32 words
    for &val in vec {
        let bytes = val.to_le_bytes();
        words.push(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]));
        words.push(u32::from_le_bytes([bytes[4], bytes[5], bytes[6], bytes[7]]));
    }
}

// RISC Zero's exact split_digest algorithm from risc0/groth16/src/verifier.rs:302-310
fn split_digest_risc0(d: risc0_zkvm::sha::Digest) -> Result<(ark_bn254::Fr, ark_bn254::Fr), Box<dyn std::error::Error>> {
    // Step 1: Convert to big-endian (RISC Zero line 303)
    let big_endian: Vec<u8> = d.as_bytes().iter().rev().cloned().collect();
    
    // Step 2: Split at middle (RISC Zero line 304-305)  
    let middle = big_endian.len() / 2;
    let (b, a) = big_endian.split_at(middle);
    
    // Step 3: Convert each half to BN254 field element (RISC Zero lines 306-309)
    let c0 = fr_from_bytes(&from_u256_hex(&hex::encode(a))?)?;  // First half -> c0
    let c1 = fr_from_bytes(&from_u256_hex(&hex::encode(b))?)?;  // Second half -> c1
    
    Ok((c0, c1))
}

// Helper functions matching RISC Zero's implementation
fn fr_from_bytes(scalar: &[u8]) -> Result<ark_bn254::Fr, Box<dyn std::error::Error>> {
    let scalar: Vec<u8> = scalar.iter().rev().cloned().collect();
    use ark_serialize::CanonicalDeserialize;
    ark_bn254::Fr::deserialize_uncompressed(&*scalar).map_err(|e| format!("Deserialization error: {}", e).into())
}

fn from_u256_hex(value: &str) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    Ok(to_fixed_array(hex::decode(value)?).to_vec())
}

fn to_fixed_array(input: Vec<u8>) -> [u8; 32] {
    let mut fixed_array = [0u8; 32];
    let start = core::cmp::max(32, input.len()) - core::cmp::min(32, input.len());
    fixed_array[start..].copy_from_slice(&input[input.len().saturating_sub(32)..]);
    fixed_array
}

fn fr_to_bytes(fr: &ark_bn254::Fr) -> Vec<u8> {
    use ark_serialize::CanonicalSerialize;
    let mut buffer = Vec::new();
    fr.serialize_uncompressed(&mut buffer).unwrap();
    buffer.reverse(); // Convert to big-endian
    buffer
}

// Save receipt and journal data for gnark circuit integration
fn save_receipt_to_file(receipt: &risc0_zkvm::Receipt, journal: &PublicJournal) -> Result<(), Box<dyn std::error::Error>> {
    use risc0_zkvm::sha::Digestible;
    use std::fs::File;
    use std::io::BufWriter;
    
    println!("\n▸ \x1b[36mSaving Receipt for Gnark Integration\x1b[0m");
    
    // 1. Save complete receipt (bincode for efficiency)
    let receipt_bytes = bincode::serialize(&receipt)?;
    std::fs::write("risc0_receipt.bin", &receipt_bytes)?;
    print_tree_item(false, "Receipt binary file", "risc0_receipt.bin", &format!("{} bytes", receipt_bytes.len()));
    
    // 2. Save receipt as JSON (human readable)
    let receipt_file = File::create("risc0_receipt.json")?;
    let writer = BufWriter::new(receipt_file);
    serde_json::to_writer_pretty(writer, &receipt)?;
    print_tree_item(false, "Receipt JSON file", "risc0_receipt.json", "");
    
    // 3. Save journal digest and data for gnark public inputs
    let journal_digest = receipt.journal.digest();
    let gnark_data = serde_json::json!({
        "journal_digest": format!("0x{}", hex::encode(journal_digest.as_bytes())),
        "journal_digest_bytes": journal_digest.as_bytes().to_vec(),
        "clearing_price": journal.clearing_price,
        "in_coin": journal.in_coin,
        "in_energy": journal.in_energy,
        "out_coin": journal.out_coin,
        "out_energy": journal.out_energy,
        "participants": journal.in_coin.len(),
        "description": "RISC Zero auction journal data for gnark circuit binding constraint"
    });
    
    let gnark_file = File::create("gnark_inputs.json")?;
    let writer = BufWriter::new(gnark_file);
    serde_json::to_writer_pretty(writer, &gnark_data)?;
    print_tree_item(true, "Gnark inputs file", "gnark_inputs.json", "Journal digest + auction data");
    
    println!("\n✅ \x1b[32mFiles ready for gnark integration!\x1b[0m");
    println!("   Use journal_digest: {}", format!("0x{}", hex::encode(journal_digest.as_bytes())));
    
    Ok(())
}
