#!/bin/bash

# Script to populate circom_data folder with proof generation commands
# Usage: ./populate_circom_data.sh
# Note: This script expects input.json to already exist (generated by the Go program)

set -e  # Exit on any error

echo "=== Populating circom_data folder ==="

# Create circom_data directory if it doesn't exist
mkdir -p circom_data

# Check if required files exist
if [ ! -f "stark_verify" ]; then
    echo "Error: stark_verify executable not found"
    exit 1
fi

# Check if input.json exists (should be generated by Go program)
if [ ! -f "input.json" ]; then
    echo "Error: input.json not found"
    echo "The Go program should have generated this file before running this script"
    exit 1
fi

# Make stark_verify executable if it isn't already
chmod +x stark_verify

echo "Step 1: Running stark_verify to generate witness..."
# Run: ./stark_verify input.json witness.wtns
./stark_verify input.json witness.wtns

# Check if witness.wtns was generated
if [ ! -f "witness.wtns" ]; then
    echo "Error: witness.wtns was not generated by stark_verify"
    exit 1
fi

echo "Step 3: Running snarkjs groth16 prove..."
# Run: snarkjs groth16 prove stark_verify_final.zkey witness.wtns proof.json public.json
# Note: We need to check if stark_verify_final.zkey exists or if we need to generate/find it
if [ ! -f "stark_verify_final.zkey" ]; then
    echo "Warning: stark_verify_final.zkey not found. You may need to generate the proving key first."
    echo "Typical commands would be:"
    echo "  snarkjs groth16 setup stark_verify.r1cs powersOfTau28_hez_final_20.ptau stark_verify_0000.zkey"
    echo "  snarkjs zkey contribute stark_verify_0000.zkey stark_verify_final.zkey"
    echo "For now, attempting to continue..."
fi

# Try to run snarkjs command - user should have snarkjs installed
if command -v snarkjs >/dev/null 2>&1; then
    # snarkjs groth16 prove stark_verify_final.zkey witness.wtns proof.json public.json
    ./prover stark_verify_final.zkey witness.wtns proof.json public.json
    
    # Extract verification key if it doesn't exist
    if [ ! -f "vkey.json" ]; then
        echo "Extracting verification key..."
        snarkjs zkey export verificationkey stark_verify_final.zkey vkey.json
    fi
else
    echo "Error: snarkjs not found. Please install snarkjs:"
    echo "  npm install -g snarkjs"
    exit 1
fi

echo "Step 4: Moving files to circom_data folder..."
# Move generated files to circom_data directory
if [ -f "proof.json" ]; then
    cp proof.json circom_data/
    echo "  ✓ Copied proof.json"
fi

if [ -f "public.json" ]; then
    cp public.json circom_data/public_signals.json
    echo "  ✓ Copied public.json as public_signals.json"
fi

if [ -f "vkey.json" ]; then
    cp vkey.json circom_data/
    echo "  ✓ Copied vkey.json"
fi

echo "Step 5: Verifying circom_data folder contents..."
echo "Contents of circom_data:"
ls -la circom_data/

# Verify that we have the required files
required_files=("proof.json" "vkey.json" "public_signals.json")
missing_files=()

for file in "${required_files[@]}"; do
    if [ ! -f "circom_data/$file" ]; then
        missing_files+=("$file")
    fi
done

if [ ${#missing_files[@]} -eq 0 ]; then
    echo "✓ All required files generated successfully!"
    echo "✓ circom_data folder is ready for use"
else
    echo "✗ Missing files: ${missing_files[*]}"
    exit 1
fi

echo "=== Done! ===" 