package main

import (
	"crypto/ecdh"
	"crypto/rand"
	"encoding/json"
	"flag"
	"fmt"
	"math/big"
	mrand "math/rand"
	"os"
	"runtime"
	"strconv"
	"strings"
	"time"

	"github.com/consensys/gnark-crypto/ecc"
	bls12377 "github.com/consensys/gnark-crypto/ecc/bls12-377"
	bls12377_fr "github.com/consensys/gnark-crypto/ecc/bls12-377/fr"
	"github.com/consensys/gnark/backend/groth16"
	"github.com/consensys/gnark/constraint"
	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"
	"github.com/consensys/gnark/std/algebra/native/sw_bls12377"

	"implementation/internal/cache"
	logger "implementation/internal/logging"
	"implementation/internal/risc0"
	"implementation/internal/transactions/exchange"
	"implementation/internal/transactions/register"
	"implementation/internal/transactions/withdraw"
	"implementation/internal/zerocash"
)

// Terminal color constants
const (
	ColorReset         = "\033[0m"
	ColorRed           = "\033[31m"
	ColorGreen         = "\033[32m"
	ColorYellow        = "\033[33m"
	ColorBlue          = "\033[34m"
	ColorMagenta       = "\033[35m"
	ColorCyan          = "\033[36m"
	ColorWhite         = "\033[37m"
	ColorBrightRed     = "\033[91m"
	ColorBrightGreen   = "\033[92m"
	ColorBrightYellow  = "\033[93m"
	ColorBrightBlue    = "\033[94m"
	ColorBrightMagenta = "\033[95m"
	ColorBrightCyan    = "\033[96m"
	ColorGray          = "\033[90m"
	ColorBold          = "\033[1m"
	ColorDim           = "\033[2m"
)

// Modern formatting utilities
func colorize(color, text string) string {
	return color + text + ColorReset
}

func formatDuration(d time.Duration) string {
	if d < time.Millisecond {
		return fmt.Sprintf("%.1fμs", float64(d.Nanoseconds())/1000.0)
	} else if d < time.Second {
		return fmt.Sprintf("%.1fms", float64(d.Nanoseconds())/1000000.0)
	} else {
		return fmt.Sprintf("%.3fs", d.Seconds())
	}
}

func formatStatus(status string) string {
	switch strings.ToUpper(status) {
	case "SUCCESS", "COMPLETE", "COMPLETED", "PASSED", "READY", "CACHED", "GENERATED", "INITIALIZED", "REGISTERED", "VERIFIED":
		return colorize(ColorGreen, "✓ "+status)
	case "PROCESSING", "STARTING", "VERIFYING":
		return colorize(ColorYellow, "▸ "+status)
	case "FAILED", "ERROR":
		return colorize(ColorRed, "✗ "+status)
	case "SKIPPED":
		return colorize(ColorGray, "- "+status)
	default:
		return status
	}
}

// MarketConfig defines all configurable market parameters
type MarketConfig struct {
	// Basic market parameters
	NumParticipants int    `json:"num_participants"`
	AuctionType     string `json:"auction_type"`

	// Participant configuration
	Roles         map[int]zerocash.OrderType `json:"roles"`
	InitialCoins  []int64                    `json:"initial_coins"`
	InitialEnergy []int64                    `json:"initial_energy"`
	Orders        []zerocash.EnergyOrder     `json:"orders"`

	// Withdrawal scenario configuration
	WithdrawalMode string `json:"withdrawal_mode"` // "none", "emergency", "selective"
	WithdrawAll    bool   `json:"withdraw_all"`    // true = all participants withdraw
	WithdrawList   []int  `json:"withdraw_list"`   // specific participants (for testing)
}

// loadScenarioFromJSON loads an auction scenario from a JSON file generated by generate_auction_scenario.py
func loadScenarioFromJSON(filename string) (MarketConfig, error) {
	// Read JSON file
	data, err := os.ReadFile(filename)
	if err != nil {
		return MarketConfig{}, fmt.Errorf("failed to read scenario file: %w", err)
	}

	// Parse JSON structure
	var scenario struct {
		ScenarioName              string `json:"scenario_name"`
		Description               string `json:"description"`
		ExpectedClearingPrice     int    `json:"expected_clearing_price"`
		ExpectedTotalEnergyTraded int    `json:"expected_total_energy_traded"`
		Participants              []struct {
			ID        int `json:"id"`
			Role      int `json:"role"` // 0 = BUY, 1 = SELL
			Price     int `json:"price"`
			Quantity  int `json:"quantity"`
			InCoin    int `json:"in_coin"`
			InEnergy  int `json:"in_energy"`
			OutCoin   int `json:"out_coin"`
			OutEnergy int `json:"out_energy"`
		} `json:"participants"`
	}

	if err := json.Unmarshal(data, &scenario); err != nil {
		return MarketConfig{}, fmt.Errorf("failed to parse scenario JSON: %w", err)
	}

	// Convert to MarketConfig
	numParticipants := len(scenario.Participants)
	roles := make(map[int]zerocash.OrderType)
	initialCoins := make([]int64, numParticipants)
	initialEnergy := make([]int64, numParticipants)
	orders := make([]zerocash.EnergyOrder, numParticipants)

	for _, p := range scenario.Participants {
		if p.ID >= numParticipants {
			return MarketConfig{}, fmt.Errorf("invalid participant ID %d", p.ID)
		}

		// Set role
		if p.Role == 0 {
			roles[p.ID] = zerocash.BUY
		} else {
			roles[p.ID] = zerocash.SELL
		}

		// Set initial balances
		initialCoins[p.ID] = int64(p.InCoin)
		initialEnergy[p.ID] = int64(p.InEnergy)

		// Create order
		orders[p.ID] = zerocash.EnergyOrder{
			Type:     roles[p.ID],
			Price:    big.NewInt(int64(p.Price)),
			Quantity: big.NewInt(int64(p.Quantity)),
		}
	}

	return MarketConfig{
		NumParticipants: numParticipants,
		AuctionType:     "python-generated-scenario",
		Roles:           roles,
		InitialCoins:    initialCoins,
		InitialEnergy:   initialEnergy,
		Orders:          orders,
		WithdrawalMode:  "none",
		WithdrawAll:     false,
		WithdrawList:    []int{},
	}, nil
}

// validateConfig ensures the market configuration is valid
func validateConfig(config MarketConfig) error {
	if config.NumParticipants <= 0 {
		return fmt.Errorf("number of participants must be positive")
	}

	// Removed the divisible by 4 restriction - now supports any N

	if len(config.InitialCoins) != config.NumParticipants {
		return fmt.Errorf("initial coins array length (%d) must match number of participants (%d)",
			len(config.InitialCoins), config.NumParticipants)
	}

	if len(config.InitialEnergy) != config.NumParticipants {
		return fmt.Errorf("initial energy array length (%d) must match number of participants (%d)",
			len(config.InitialEnergy), config.NumParticipants)
	}

	if len(config.Orders) != config.NumParticipants {
		return fmt.Errorf("orders array length (%d) must match number of participants (%d)",
			len(config.Orders), config.NumParticipants)
	}

	if len(config.Roles) != config.NumParticipants {
		return fmt.Errorf("roles map length (%d) must match number of participants (%d)",
			len(config.Roles), config.NumParticipants)
	}

	// Validate withdrawal configuration
	if config.WithdrawalMode == "selective" && len(config.WithdrawList) == 0 {
		return fmt.Errorf("selective withdrawal mode requires non-empty withdraw list")
	}

	for _, id := range config.WithdrawList {
		if id < 0 || id >= config.NumParticipants {
			return fmt.Errorf("withdraw list contains invalid participant ID: %d", id)
		}
	}

	return nil
}

// Protocol configuration - now using MarketConfig instead of hardcoded values

// ProtocolState holds all the state needed for the PPEM protocol execution
type ProtocolState struct {
	// Market configuration
	Config MarketConfig

	// Cryptographic keys and parameters
	AuctioneerDHKp      *zerocash.DHKeyPair
	AuctioneerECDHPriv  *ecdh.PrivateKey
	AuctioneerECDHPub   *ecdh.PublicKey
	ParticipantDHKeys   []*zerocash.DHKeyPair
	ParticipantECDHKeys []*ecdh.PrivateKey
	CircuitKeys         *CircuitKeys

	// Participants and their data
	Participants  []*zerocash.Participant
	BaseNotes     []*zerocash.Note
	BaseNoteKeys  [][]byte
	OrderPrices   []*big.Int // Order prices for each participant
	SharedSecrets []*bls12377.G1Affine

	// Protocol execution data
	Ledger             *zerocash.Ledger
	RegistrationTxs    []*zerocash.Tx
	RegistrationProofs [][]byte
	ExchangeProof      []byte
	WithdrawalResults  []bool
	WithdrawalAttempts int // Track number of actual withdrawal attempts

	// Batch withdrawal data for ledger verification
	WithdrawalTxs    []*zerocash.Tx
	WithdrawalProofs [][]byte
	WithdrawalData   []map[string]interface{}
	WithdrawalIDs    []int

	// RISC Zero integration (always enabled)
	RISC0ProofData *risc0.RISC0ProofData // RISC Zero proof data from auction

	// Algorithm 2 outputs (Registration keypairs that must be stored)
	ParticipantSkIn  []*big.Int    // sk^in: Secret keys for notes TO auctioneer
	ParticipantPkIn  []*big.Int    // pk^in: Public keys for notes TO auctioneer
	ParticipantSkOut []*big.Int    // sk^out: Secret keys for notes FROM auctioneer
	ParticipantPkOut []*big.Int    // pk^out: Public keys for notes FROM auctioneer
	ParticipantCAux  [][7]*big.Int // C^Aux: Encrypted registration data (7 fields: pk, sk, bid, coins, energy, role, quantity)
}

// CircuitKeys holds all the cryptographic circuit keys needed for ZK proofs
type CircuitKeys struct {
	// Core transaction circuits
	pkTx, pkReg, pkWithdraw    groth16.ProvingKey
	vkTx, vkReg, vkWithdraw    groth16.VerifyingKey
	ccsTx, ccsReg, ccsWithdraw constraint.ConstraintSystem

	// Dynamic circuit manager for any N participants
	DynamicManager interface {
		GetOrCreateCircuitKeys(n int) (*exchange.CircuitKeys, error)
		PrecompileCircuits(counts []int) error
	}
}

func main() {
	// Parse command-line flags
	var numParticipants int
	var scenarioFile string
	var verbose bool
	var quiet bool
	var verbosity string
	var withdrawAll bool
	var withdrawListStr string

	flag.IntVar(&numParticipants, "n", 10, "Number of participants (positive integer)")
	flag.StringVar(&scenarioFile, "scenario", "", "Path to auction scenario JSON file (default: risc0/auction_scenario_N{participants}.json)")
	flag.BoolVar(&verbose, "verbose", false, "Enable verbose output (equivalent to -verbosity=debug)")
	flag.BoolVar(&quiet, "quiet", false, "Suppress informational output (equivalent to -verbosity=quiet)")
	flag.StringVar(&verbosity, "verbosity", "info", "Verbosity level: quiet, info, debug, trace")
	flag.BoolVar(&withdrawAll, "withdraw-all", false, "After finalization, withdraw for all participants")
	flag.StringVar(&withdrawListStr, "withdraw-list", "", "Comma-separated participant IDs to withdraw (0-based)")
	flag.Parse()

	// Seed RNG for non-deterministic scenarios
	mrand.Seed(time.Now().UnixNano())

	// Setup logger
	logger.Setup(verbosity)

	// Validate input parameters
	if numParticipants <= 0 {
		printError("Invalid Configuration", fmt.Sprintf("Participants must be positive, got %d", numParticipants))
	}

	startTime := time.Now()

	// STEP 1: Load market scenario from JSON file
	if scenarioFile == "" {
		scenarioFile = fmt.Sprintf("risc0/auction_scenario_N%d.json", numParticipants)
	}
	config, err := loadScenarioFromJSON(scenarioFile)
	if err != nil {
		if scenarioFile == fmt.Sprintf("risc0/auction_scenario_N%d.json", numParticipants) {
			// Default file - suggest generation
			printError("Scenario Loading", fmt.Sprintf("Failed to load %s: %s\nGenerate it first: python3 generate_auction_scenario.py %d", scenarioFile, err.Error(), numParticipants))
		} else {
			// Custom file - just show the error
			printError("Scenario Loading", fmt.Sprintf("Failed to load %s: %s", scenarioFile, err.Error()))
		}
	}

	// Apply withdrawal flags to configuration (overrides scenario defaults)
	if withdrawAll {
		config.WithdrawalMode = "all"
		config.WithdrawAll = true
		config.WithdrawList = []int{}
	} else if strings.TrimSpace(withdrawListStr) != "" {
		parts := strings.Split(withdrawListStr, ",")
		list := make([]int, 0, len(parts))
		for _, p := range parts {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			idx, convErr := strconv.Atoi(p)
			if convErr != nil {
				printError("Configuration", fmt.Sprintf("invalid withdraw-list entry '%s'", p))
			}
			list = append(list, idx)
		}
		config.WithdrawalMode = "selective"
		config.WithdrawAll = false
		config.WithdrawList = list
	}

	// Print protocol header with actual buyer ratio from loaded config
	if !quiet {
		buyerRatio := getBuyerRatio(config.Roles)
		printProtocolHeader(config.NumParticipants, buyerRatio, verbosity)
	}

	// Validate configuration
	if err := validateConfig(config); err != nil {
		printError("Configuration", err.Error())
	}

	// Update numParticipants to match the loaded scenario
	numParticipants = config.NumParticipants

	// PHASE 1: SETUP
	if !quiet {
		printPhaseHeader(1, "PROTOCOL SETUP")
	}
	state := &ProtocolState{
		Config:             config,
		Participants:       make([]*zerocash.Participant, config.NumParticipants),
		BaseNotes:          make([]*zerocash.Note, config.NumParticipants),
		BaseNoteKeys:       make([][]byte, config.NumParticipants),
		OrderPrices:        make([]*big.Int, config.NumParticipants),
		SharedSecrets:      make([]*bls12377.G1Affine, config.NumParticipants),
		ParticipantSkIn:    make([]*big.Int, config.NumParticipants),
		ParticipantPkIn:    make([]*big.Int, config.NumParticipants),
		ParticipantSkOut:   make([]*big.Int, config.NumParticipants),
		ParticipantPkOut:   make([]*big.Int, config.NumParticipants),
		ParticipantCAux:    make([][7]*big.Int, config.NumParticipants),
		RegistrationTxs:    make([]*zerocash.Tx, config.NumParticipants),
		RegistrationProofs: make([][]byte, config.NumParticipants),
		WithdrawalResults:  make([]bool, config.NumParticipants),
	}
	setupStart := time.Now()
	if err := setupProtocol(state); err != nil {
		printError("Setup", err.Error())
	}
	setupDuration := time.Since(setupStart)
	if !quiet {
		printPhaseComplete(setupDuration)
	}

	// PHASE 2: REGISTRATION
	if !quiet {
		printPhaseHeader(2, "PARTICIPANT REGISTRATION")
	}
	regStart := time.Now()
	if err := executeRegistrationPhase(state); err != nil {
		printError("Registration", err.Error())
	}
	regDuration := time.Since(regStart)
	if !quiet {
		printPhaseComplete(regDuration)
	}

	// Emergency withdrawal path: if requested, skip auction and perform withdrawals immediately
	withdrawalRequested := state.Config.WithdrawAll || (state.Config.WithdrawalMode == "selective" && len(state.Config.WithdrawList) > 0)
	if withdrawalRequested {
		// Move ledger from Registration -> Exchange -> Withdraw without spending registration notes
		if err := state.Ledger.StartExchangePhase(); err != nil {
			printError("Withdraw", fmt.Sprintf("failed to start exchange phase: %s", err.Error()))
		}
		if err := state.Ledger.CloseAuction(); err != nil {
			printError("Withdraw", fmt.Sprintf("failed to enter withdraw phase: %s", err.Error()))
		}

		// Execute withdrawals now (no auction run)
		if !quiet {
			printPhaseHeader(5, "WITHDRAWAL PROCESSING")
		}
		withStart := time.Now()
		executeWithdrawalDemo(state)
		withDuration := time.Since(withStart)
		if !quiet {
			printPhaseComplete(withDuration)
		}

		// Summary and exit
		totalTime := time.Since(startTime)
		if !quiet {
			phaseTiming := &PhaseTiming{
				Setup:        setupDuration,
				Registration: regDuration,
				Exchange:     0, // skipped
				Finalization: 0, // skipped
				Withdrawal:   withDuration,
			}
			printProtocolSummary(state, totalTime, phaseTiming)
		}
		return
	}

	// PHASE 3: EXCHANGE
	if !quiet {
		printPhaseHeader(3, "AUCTION EXECUTION")
	}
	exchStart := time.Now()
	if err := executeExchangePhase(state); err != nil {
		printError("Exchange", err.Error())
	}
	exchDuration := time.Since(exchStart)
	if !quiet {
		printPhaseComplete(exchDuration)
	}

	// PHASE 4: FINALIZATION
	if !quiet {
		printPhaseHeader(4, "PROTOCOL FINALIZATION")
	}
	finStart := time.Now()
	if err := executeFinalizationPhase(state); err != nil {
		printError("Finalization", err.Error())
	}
	finDuration := time.Since(finStart)
	if !quiet {
		printPhaseComplete(finDuration)
	}

	// PHASE 5: WITHDRAWAL
	if !quiet {
		printPhaseHeader(5, "WITHDRAWAL PROCESSING")
	}
	withStart := time.Now()
	executeWithdrawalDemo(state)
	withDuration := time.Since(withStart)
	if !quiet {
		printPhaseComplete(withDuration)
	}

	// SUMMARY
	totalTime := time.Since(startTime)
	if !quiet {
		phaseTiming := &PhaseTiming{
			Setup:        setupDuration,
			Registration: regDuration,
			Exchange:     exchDuration,
			Finalization: finDuration,
			Withdrawal:   withDuration,
		}
		printProtocolSummary(state, totalTime, phaseTiming)
	}
}

// setupProtocol implements the initial setup phase including key generation and circuit compilation
func setupProtocol(state *ProtocolState) error {
	if state == nil {
		return fmt.Errorf("nil state")
	}
	if err := func() error {
		// Circuit Compilation
		if !quiet {
			printStep(0, 0, "Circuit Compilation")
		}

		// Compile fixed circuits and dynamic exchange circuit
		var err error
		state.CircuitKeys, err = setupCircuitKeys(state.Config.NumParticipants)
		if err != nil {
			return fmt.Errorf("circuit setup failed: %w", err)
		}

		if !quiet {
			fmt.Println()
		}

		// Generate keys (auctioneer + participants)
		if !quiet {
			printStep(0, 0, "Cryptographic Keys")
		}
		keysGenStart := time.Now()
		var kerr error
		state.AuctioneerDHKp, kerr = zerocash.GenerateDHKeyPair()
		if kerr != nil {
			return fmt.Errorf("auctioneer key generation failed: %w", kerr)
		}
		state.AuctioneerECDHPriv, kerr = ecdh.P256().GenerateKey(rand.Reader)
		if kerr != nil {
			return fmt.Errorf("auctioneer key generation failed: %w", kerr)
		}
		state.AuctioneerECDHPub = state.AuctioneerECDHPriv.PublicKey()

		state.ParticipantDHKeys = make([]*zerocash.DHKeyPair, state.Config.NumParticipants)
		state.ParticipantECDHKeys = make([]*ecdh.PrivateKey, state.Config.NumParticipants)
		for i := 0; i < state.Config.NumParticipants; i++ {
			state.ParticipantDHKeys[i], kerr = zerocash.GenerateDHKeyPair()
			if kerr != nil {
				return fmt.Errorf("participant %d DH key generation failed: %w", i, kerr)
			}
			state.ParticipantECDHKeys[i], kerr = ecdh.P256().GenerateKey(rand.Reader)
			if kerr != nil {
				return fmt.Errorf("participant %d ECDH key generation failed: %w", i, kerr)
			}
		}
		if !quiet {
			printTreeItem(false, "Auctioneer keypair", "GENERATED", 0)
			printTreeItem(true, fmt.Sprintf("Participant keypairs [N=%d]", state.Config.NumParticipants), "GENERATED", time.Since(keysGenStart))
		}

		if !quiet {
			fmt.Println()
		}

		// Market scenario and ledger setup
		if !quiet {
			printStep(0, 0, "Ledger Initialization")
		}

		ledgerStart := time.Now()
		// Participants, base notes, ledger init
		state.Participants = make([]*zerocash.Participant, state.Config.NumParticipants)
		state.BaseNotes = make([]*zerocash.Note, state.Config.NumParticipants)
		state.BaseNoteKeys = make([][]byte, state.Config.NumParticipants)
		state.OrderPrices = make([]*big.Int, state.Config.NumParticipants)
		state.SharedSecrets = make([]*bls12377.G1Affine, state.Config.NumParticipants)

		for i := 0; i < state.Config.NumParticipants; i++ {
			state.Participants[i] = &zerocash.Participant{
				Name:          fmt.Sprintf("Participant_%02d", i+1),
				Sk:            state.ParticipantDHKeys[i].Sk,
				Pk:            state.ParticipantDHKeys[i].Pk,
				Role:          zerocash.RoleParticipant,
				AuctioneerPub: state.AuctioneerDHKp.Pk,
				Params:        &zerocash.Params{},
				Wallet:        &zerocash.Wallet{Name: fmt.Sprintf("Participant_%02d", i+1), Sk: state.ParticipantDHKeys[i].Sk, Pk: state.ParticipantDHKeys[i].Pk},
			}
			coins := big.NewInt(state.Config.InitialCoins[i])
			energy := big.NewInt(state.Config.InitialEnergy[i])
			state.OrderPrices[i] = new(big.Int).Set(state.Config.Orders[i].Price)
			state.BaseNoteKeys[i] = zerocash.RandomBytesPublic(32)
			state.BaseNotes[i] = zerocash.NewNote(coins, energy, state.BaseNoteKeys[i])
			state.Participants[i].Wallet.AddNote(state.BaseNotes[i], state.BaseNoteKeys[i], []byte{}, [5]byte{}, state.BaseNotes[i])
			state.SharedSecrets[i] = zerocash.ComputeDHShared(state.ParticipantDHKeys[i].Sk, state.AuctioneerDHKp.Pk)
		}

		// Initialize fresh ledger
		state.Ledger = zerocash.NewLedger()
		// Set actual circuit keys for verification
		ledgerKeys := &zerocash.CircuitKeys{
			VkTx:   state.CircuitKeys.vkTx,
			CcsTx:  state.CircuitKeys.ccsTx,
			VkReg:  state.CircuitKeys.vkReg,
			CcsReg: state.CircuitKeys.ccsReg,
		}
		// Set exchange keys from dynamic manager if available
		if state.CircuitKeys.DynamicManager != nil {
			if manager, ok := state.CircuitKeys.DynamicManager.(*SimpleExchangeManager); ok {
				ledgerKeys.VkExchange = manager.vk
				ledgerKeys.CcsExchange = manager.ccs
			}
		}

		// Note: Withdrawal keys will be set later when needed since they're compiled on-demand
		state.Ledger.SetCircuitKeys(ledgerKeys)
		state.Ledger.SetAuctioneerKeys(state.AuctioneerDHKp.Pk, state.AuctioneerECDHPub)
		for i := range state.BaseNotes {
			cmBase := new(big.Int).SetBytes(state.BaseNotes[i].Cm).String()
			state.Ledger.CmList = append(state.Ledger.CmList, cmBase)
		}

		if !quiet {
			printTreeItem(false, "Participants", fmt.Sprintf("%d created", state.Config.NumParticipants), 0)
			printTreeItem(false, "Base notes", fmt.Sprintf("%d initialized", len(state.BaseNotes)), 0)
			printTreeItem(true, "Ledger", "INITIALIZED", time.Since(ledgerStart))
		}
		return nil
	}(); err != nil {
		return err
	}
	return nil
}

// executeRegistrationPhase handles participant registration
func executeRegistrationPhase(state *ProtocolState) error {
	if err := state.Ledger.StartRegistrationPhase(); err != nil {
		return fmt.Errorf("failed to start registration phase: %w", err)
	}

	if !quiet {
		printStep(0, 0, "Participant Registration Processing")
		fmt.Printf("%s Registration phase initiated\n", colorize(ColorCyan, "▸"))
		fmt.Println()
	}

	// First pass: build all registration transactions and proofs
	registerResults := make([]*register.RegisterResult, state.Config.NumParticipants)
	var proofs int
	buildStart := time.Now()
	for i := 0; i < state.Config.NumParticipants; i++ {
		participantStart := time.Now()
		if !quiet {
			fmt.Printf("Participant %02d                                        %s\n",
				i+1, formatStatus("PROCESSING"))
		}

		role := state.Config.Roles[i]
		res, err := register.Register(
			state.Participants[i], state.BaseNotes[i], state.OrderPrices[i], int(role), state.Config.Orders[i].Quantity.Int64(),
			state.CircuitKeys.pkTx, state.CircuitKeys.ccsTx, state.CircuitKeys.pkReg, state.CircuitKeys.ccsReg,
			state.BaseNoteKeys[i], state.AuctioneerECDHPub, state.ParticipantECDHKeys[i],
		)
		if err != nil {
			if !quiet {
				fmt.Printf("Participant %02d                                        %s\n",
					i+1, formatStatus("FAILED"))
			}
			return fmt.Errorf("registration failed for participant %d: %w", i, err)
		}
		registerResults[i] = res
		proofs++

		if !quiet {
			fmt.Printf("Participant %02d                                        %s %s\n",
				i+1,
				formatStatus("SUCCESS"),
				colorize(ColorGray, formatDuration(time.Since(participantStart))))
			// Add separator line between participants (except for the last one)
			if i < state.Config.NumParticipants-1 {
				fmt.Printf("%s\n", colorize(ColorGray, "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
			}
		}
	}

	if !quiet {
		fmt.Printf("\nRegistration Build Summary → %s proofs generated %s\n\n",
			colorize(ColorBold, fmt.Sprintf("%d/%d", proofs, state.Config.NumParticipants)),
			colorize(ColorGray, formatDuration(time.Since(buildStart))))
	}

	// Second pass: ledger verification (proof verification + ledger updates)
	if !quiet {
		printStep(0, 0, "Ledger Verification")
	}

	var verifiedProofs int
	verifyStart := time.Now()
	for i := 0; i < state.Config.NumParticipants; i++ {
		res := registerResults[i]
		if res == nil {
			continue
		}

		err := state.Ledger.SubmitRegistration(
			res.TxIn, res.PublicInputs, res.Proof, fmt.Sprintf("participant_%d", i),
		)
		if err != nil {
			if !quiet {
				fmt.Printf("Participant %02d      TX: %s • Reg: %s     → %s\n",
					i+1,
					colorize(ColorRed, "✗ FAILED"),
					colorize(ColorRed, "✗ FAILED"),
					colorize(ColorRed, "FAILED"))
			}
			continue
		}

		// Store successful registration
		state.RegistrationTxs[i] = res.TxIn
		state.RegistrationProofs[i] = res.Proof
		state.ParticipantSkIn[i] = res.SkIn
		state.ParticipantPkIn[i] = res.PkIn
		state.ParticipantSkOut[i] = res.SkOut
		state.ParticipantPkOut[i] = res.PkOut
		state.ParticipantCAux[i] = res.CAux
		verifiedProofs++

		if !quiet {
			fmt.Printf("Participant %02d      TX: %s • Reg: %s     → %s\n",
				i+1,
				colorize(ColorGreen, "✓ PASSED"),
				colorize(ColorGreen, "✓ PASSED"),
				colorize(ColorGreen, "REGISTERED"))
		}
	}

	if !quiet {
		fmt.Printf("\nVerification Summary → %s participants verified %s\n",
			colorize(ColorBold, fmt.Sprintf("%d/%d", verifiedProofs, state.Config.NumParticipants)),
			colorize(ColorGray, formatDuration(time.Since(verifyStart))))
	}
	return nil
}

// executeExchangePhase handles the energy market auction
func executeExchangePhase(state *ProtocolState) error {
	if !quiet {
		printStep(0, 0, "Auction Payload Preparation")
	}
	decryptStart := time.Now()
	// build payloads (unchanged)
	// NOTE: Participants will be sorted by the exchange phase according to their roles:
	// - Buyers will be sorted by bid (descending - highest to lowest)
	// - Sellers will be sorted by ask (ascending - lowest to highest)
	// - Number of buyers/sellers is configurable via buyer-ratio parameter
	exchangePayloads := make([]exchange.RegistrationPayload, state.Config.NumParticipants)
	participantECDHPubKeys := make([]*ecdh.PublicKey, state.Config.NumParticipants)

	for i := 0; i < state.Config.NumParticipants; i++ {
		exchangePayloads[i] = exchange.RegistrationPayload{
			Ciphertext: state.ParticipantCAux[i],
			PubKey: &sw_bls12377.G1Affine{
				X: state.ParticipantDHKeys[i].Pk.X.String(),
				Y: state.ParticipantDHKeys[i].Pk.Y.String(),
			},
			TxNoteData: state.RegistrationTxs[i].CNew, // Use encrypted note data from Algorithm 1
		}
		participantECDHPubKeys[i] = state.ParticipantECDHKeys[i].PublicKey()
	}

	// Prepare DH private keys for circuit
	participantDHPrivKeys := make([]*bls12377_fr.Element, state.Config.NumParticipants)
	for i := 0; i < state.Config.NumParticipants; i++ {
		participantDHPrivKeys[i] = state.ParticipantDHKeys[i].Sk
	}

	// Declare variables that will be used after the if-else block
	var exchangeTx interface{}
	var auctionInfo interface{}
	var exchangeProof []byte
	var risc0Data *risc0.RISC0ProofData // Declare risc0Data here
	var err error

	if !quiet {
		printTreeItem(false, "Registration payloads", fmt.Sprintf("%d prepared", len(exchangePayloads)), 0)
		printTreeItem(false, "ECDH public keys", fmt.Sprintf("%d prepared", len(participantECDHPubKeys)), 0)
		printTreeItem(true, "DH private keys", fmt.Sprintf("%d prepared", len(participantDHPrivKeys)), time.Since(decryptStart))
		fmt.Println()

		printStep(0, 0, "Auction Execution & Proof Generation")
		fmt.Printf("%s Exchange processing: %s\n",
			colorize(ColorCyan, "▸"),
			formatStatus("STARTING"))
	}

	// Get dynamic circuit keys for the actual number of participants
	dynamicKeys, err := state.CircuitKeys.DynamicManager.GetOrCreateCircuitKeys(state.Config.NumParticipants)
	if err != nil {
		return fmt.Errorf("failed to get circuit keys for %d participants: %w", state.Config.NumParticipants, err)
	}

	// THIS SINGLE CALL DOES EVERYTHING: decryption + auction + RISC0 + proof generation + ledger submission
	var exchangePublicInputs interface{}
	exchangeTx, auctionInfo, exchangeProof, risc0Data, exchangePublicInputs, err = exchange.ExchangePhaseWithNotes(
		exchangePayloads,
		state.AuctioneerDHKp.Sk.BigInt(new(big.Int)),
		state.AuctioneerECDHPriv,
		participantECDHPubKeys,
		participantDHPrivKeys,
		state.AuctioneerDHKp.Pk,
		state.Config.Roles,
		state.Ledger,
		&zerocash.Params{},
		dynamicKeys.ProvingKey,
		dynamicKeys.ConstraintSystem,
	)
	if err != nil {
		// Enhanced error handling for RISC Zero related failures
		errMsg := err.Error()
		if strings.Contains(errMsg, "risc0") || strings.Contains(errMsg, "RISC0") {
			return fmt.Errorf("RISC Zero proof generation failed: %w\nThis may be due to:\n  - Missing RISC Zero dependencies (cargo, snarkjs)\n  - Insufficient memory or disk space\n  - Missing circuit files\nCheck the RISC0_INTEGRATION.md for setup instructions", err)
		}
		return fmt.Errorf("exchange execution failed: %w", err)
	}

	state.ExchangeProof = exchangeProof
	state.RISC0ProofData = risc0Data

	if !quiet {
		printTreeItem(false, "Registration decryption", "COMPLETED", 0)
		printTreeItem(false, "Auction computation", "COMPLETED", 0)
		printTreeItem(false, "RISC Zero verification", "COMPLETED", 0)
		printTreeItem(false, "ZK proof generation", "COMPLETED", 0)
	}

	// Create graphs subdirectory and process results
	graphsDir := "graphs"
	if err := os.MkdirAll(graphsDir, 0755); err != nil {
		if !quiet {
			printTreeItem(true, "Graph directory creation", "FAILED", 0)
		}
	} else {
		// Extract auction execution result for plotting
		if compositeResult, ok := auctionInfo.(struct {
			AuctionResult    *exchange.AuctionResult
			AuctionExecution *exchange.AuctionExecutionResult
		}); ok {
			// Create timestamp for unique filenames
			timestamp := time.Now().Format("20060102_150405")
			plotTitle := fmt.Sprintf("PPEM_N%d_Buyers%.0f%%_%s",
				state.Config.NumParticipants,
				getBuyerRatio(state.Config.Roles)*100,
				timestamp)

			// Create plot configuration
			config := exchange.DefaultPlotConfig()
			config.OutputPath = fmt.Sprintf("%s/%s.png", graphsDir, plotTitle)
			config.Title = fmt.Sprintf("N=%d (%d buyers, %d sellers) | Clearing: %v | Traded: %d units",
				state.Config.NumParticipants,
				countBuyers(state.Config.Roles),
				countSellers(state.Config.Roles),
				compositeResult.AuctionExecution.ClearingPrice,
				compositeResult.AuctionExecution.TotalEnergyTraded)

			// Create inputs array for plotting (reconstruct from exchange data)
			inputs := make([]exchange.DecryptedRegistration, 0)
			if exchangeResult, ok := exchangeTx.(*exchange.ExchangeTransaction); ok {
				for i, output := range exchangeResult.Outputs {
					if i < len(state.Config.Orders) {
						input := exchange.DecryptedRegistration{
							Price:    state.Config.Orders[i].Price,
							Quantity: state.Config.Orders[i].Quantity,
							Coins:    output.Coins,
							Energy:   output.Energy,
						}
						inputs = append(inputs, input)
					}
				}
			}

			// Generate the plot
			err := exchange.CreateSupplyDemandPlot(inputs, state.Config.Roles, compositeResult.AuctionExecution, config)
			if err != nil {
				if !quiet {
					printTreeItem(false, "Auction visualization", "FAILED", 0)
				}
			} else {
				if !quiet {
					printTreeItem(false, "Auction visualization", "saved to graphs/", 0)
					printTreeItem(false, "Clearing price", fmt.Sprintf("%v coins/unit", compositeResult.AuctionExecution.ClearingPrice), 0)
					printTreeItem(false, "Volume traded", fmt.Sprintf("%d energy units", compositeResult.AuctionExecution.TotalEnergyTraded), 0)
				}
			}

			// Generate JSON export with detailed exchange mappings
			exportDir := "exchange_data"
			if err := os.MkdirAll(exportDir, 0755); err != nil {
				if !quiet {
					printTreeItem(false, "Exchange data export", "FAILED", 0)
				}
			} else {
				jsonFilename := fmt.Sprintf("%s.json", plotTitle)
				err = exchange.ExportAuctionToJSON(inputs, state.Config.Roles, compositeResult.AuctionExecution, exportDir, jsonFilename)
				if err != nil {
					if !quiet {
						printTreeItem(false, "Exchange data export", "FAILED", 0)
					}
				} else {
					if !quiet {
						printTreeItem(false, "Exchange data export", "saved to exchange_data/", 0)
					}
				}
			}
		}
	}

	if !quiet {
		printTreeItem(false, "Output transactions", fmt.Sprintf("%d created", state.Config.NumParticipants), 0)
		printTreeItem(true, "Ledger state update", "COMPLETED", 0)
	}

	outputTxs := make([]*zerocash.Tx, 0)

	if exchangeResult, ok := exchangeTx.(*exchange.ExchangeTransaction); ok {
		// Generate proper Algorithm 1 proofs for each output transaction
		for i, output := range exchangeResult.Outputs {
			if i < len(state.RegistrationTxs) && output.Coins != nil && output.Energy != nil {
				// Use the input note from registration phase
				inputNote := state.RegistrationTxs[i].NewNote

				// Use the participant's input secret key (stored during registration)
				// Convert from big.Int to byte array using natural size
				skInBytes := state.ParticipantSkIn[i].Bytes()

				// Use the participant's output public key (stored during registration)
				// Convert from big.Int to byte array using natural size
				pkOutBytes := state.ParticipantPkOut[i].Bytes()

				fmt.Printf("\x1b[33m▪ Output TX %02d (10658 constraints)\x1b[0m\n", i+1)
				outputTx, err := zerocash.CreateTx(
					inputNote,                    // Input note from registration
					skInBytes,                    // Secret key for input note
					pkOutBytes,                   // Public key for output note
					output.Coins,                 // New coin amount (from auction)
					output.Energy,                // New energy amount (from auction)
					&zerocash.Params{},           // Protocol parameters
					state.CircuitKeys.ccsTx,      // Transaction circuit
					state.CircuitKeys.pkTx,       // Transaction proving key
					state.AuctioneerECDHPub,      // Auctioneer's ECDH public key
					state.ParticipantECDHKeys[i], // Participant's ECDH private key
				)
				if err != nil {
					return fmt.Errorf("failed to create output transaction %d: %w", i, err)
				}

				outputTxs = append(outputTxs, outputTx)
				// Add separator line between output TXs (except for the last one)
				if i < len(exchangeResult.Outputs)-1 && !quiet {
					fmt.Printf("%s\n", colorize(ColorGray, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
				}
			}
		}
	}

	// LEDGER VERIFICATION SECTION
	if !quiet {
		printStep(3, 3, "Ledger Verification")
	}

	verificationStart := time.Now()

	// Transition ledger to exchange phase before submitting results
	if err := state.Ledger.StartExchangePhase(); err != nil {
		return fmt.Errorf("failed to start exchange phase: %w", err)
	}

	if !quiet {
		fmt.Printf("%s Exchange proof: %s\n",
			colorize(ColorCyan, "▸"),
			formatStatus("VERIFYING"))
	}

	// Submit exchange results to ledger with individual output transactions including public inputs for verification
	auctionInfoBytes := []byte(fmt.Sprintf(`{"auction_type":"sealed_bid_double_auction","participants":%d}`, state.Config.NumParticipants))
	err = state.Ledger.SubmitExchange(outputTxs, state.ExchangeProof, auctionInfoBytes, exchangePublicInputs)
	if err != nil {
		return fmt.Errorf("failed to submit exchange results: %w", err)
	}

	if !quiet {
		printTreeItem(false, "Exchange proof", "VERIFIED", 0)
		printTreeItem(true, "Ledger submission", "COMPLETED", time.Since(verificationStart))
	}

	// Phase completion handled in main function
	return nil
}

// executeFinalizationPhase finalizes the protocol
func executeFinalizationPhase(state *ProtocolState) error {
	if !quiet {
		printStep(0, 0, "Auction Closure")
	}
	closureStart := time.Now()
	if err := state.Ledger.CloseAuction(); err != nil {
		return fmt.Errorf("failed to close auction: %w", err)
	}
	if !quiet {
		printTreeItem(false, "Output commitment", "FINALIZED", 0)
		printTreeItem(true, "State persistence", "COMPLETED", time.Since(closureStart))
		fmt.Println()

		printStep(0, 0, "Data Export")
	}

	exportStart := time.Now()
	if err := state.Ledger.SaveToFile("ledger_final.json"); err == nil {
		if !quiet {
			printTreeItem(false, "Final ledger", "saved to ledger_final.json", 0)
		}
	} else {
		if !quiet {
			printTreeItem(false, "Final ledger", "FAILED", 0)
		}
	}
	if !quiet {
		printTreeItem(true, "Protocol state", fmt.Sprintf("%d commitments, %d serials, %d transactions",
			len(state.Ledger.CmList), len(state.Ledger.SnList), len(state.Ledger.TxList)), time.Since(exportStart))
	}
	return nil
}

// executeWithdrawalDemo demonstrates emergency withdrawal functionality
func executeWithdrawalDemo(state *ProtocolState) {
	// Check withdrawal mode from configuration
	if state.Config.WithdrawalMode == "none" {
		if !quiet {
			fmt.Printf("%s Withdrawal mode: %s\n",
				colorize(ColorCyan, "▸"),
				formatStatus("SKIPPED")+colorize(ColorGray, " (none)"))
		}
		state.WithdrawalAttempts = 0
		return
	}

	// Setup withdrawal circuit keys
	withdrawalKeys, err := setupWithdrawalKeys()
	if err != nil {
		if !quiet {
			fmt.Printf("%s Withdrawal setup: %s\n",
				colorize(ColorCyan, "▸"),
				formatStatus("FAILED"))
		}
		return
	}

	// Update ledger with withdrawal keys
	currentKeys := state.Ledger.GetCircuitKeys()
	if currentKeys != nil {
		currentKeys.VkWithdraw = withdrawalKeys.vkWithdraw
		currentKeys.CcsWithdraw = withdrawalKeys.ccsWithdraw
		state.Ledger.SetCircuitKeys(currentKeys)
	}

	// Determine which participants should withdraw
	var participantsToWithdraw []int
	if state.Config.WithdrawAll {
		// All participants withdraw
		participantsToWithdraw = make([]int, state.Config.NumParticipants)
		for i := 0; i < state.Config.NumParticipants; i++ {
			participantsToWithdraw[i] = i
		}
	} else if len(state.Config.WithdrawList) > 0 {
		// Specific participants withdraw
		participantsToWithdraw = state.Config.WithdrawList
	} else {
		// No withdrawals
		if !quiet {
			fmt.Printf("%s Withdrawal mode: %s\n",
				colorize(ColorCyan, "▸"),
				formatStatus("SKIPPED")+colorize(ColorGray, " (none)"))
		}
		state.WithdrawalAttempts = 0
		return
	}

	if !quiet {
		fmt.Printf("%s Withdrawal requests: %s participants\n",
			colorize(ColorCyan, "▸"),
			colorize(ColorBold, fmt.Sprintf("%d", len(participantsToWithdraw))))
		fmt.Printf("%s Withdrawal circuit: %s\n",
			colorize(ColorCyan, "▸"),
			formatStatus("STARTING"))
		fmt.Println()
	}
	state.WithdrawalAttempts = len(participantsToWithdraw)

	successCount := 0
	for i, participantID := range participantsToWithdraw {
		participantStart := time.Now()
		if participantID >= state.Config.NumParticipants {
			if !quiet {
				fmt.Printf("Participant %02d                                     %s\n",
					participantID+1, formatStatus("INVALID ID"))
			}
			continue
		}

		if !quiet {
			fmt.Printf("Participant %02d                                     %s\n",
				participantID+1, formatStatus("PROCESSING"))
		}

		// Use the note created during registration
		registrationTx := state.RegistrationTxs[participantID]
		noteToWithdraw := registrationTx.NewNote
		skIn := state.ParticipantSkIn[participantID]

		// Create withdrawal note data structures
		inNote := withdraw.Note{
			Coins:  noteToWithdraw.Value.Coins,
			Energy: noteToWithdraw.Value.Energy,
			Pk:     new(big.Int).SetBytes(noteToWithdraw.PkOwner),
			Rho:    new(big.Int).SetBytes(noteToWithdraw.Rho),
			R:      new(big.Int).SetBytes(noteToWithdraw.Rand),
			Cm:     new(big.Int).SetBytes(noteToWithdraw.Cm),
		}

		fmt.Printf("\x1b[31m  ▪ Withdrawal TX %02d (10658 constraints)\x1b[0m\n", participantID+1)
		skInBytes := skIn.Bytes()
		pkOutBytes := state.ParticipantPkOut[participantID].Bytes()
		outputTx, err := zerocash.CreateTx(
			noteToWithdraw,             // Input note from registration
			skInBytes,                  // Secret key for input note
			pkOutBytes,                 // Public key for output note
			noteToWithdraw.Value.Coins, // Preserve balances on emergency withdraw
			noteToWithdraw.Value.Energy,
			&zerocash.Params{},
			state.CircuitKeys.ccsTx,
			state.CircuitKeys.pkTx,
			state.AuctioneerECDHPub,
			state.ParticipantECDHKeys[participantID],
		)
		if err != nil {
			if !quiet {
				fmt.Printf("Participant %02d                                     %s %s\n",
					participantID+1,
					formatStatus("TX BUILD FAILED"),
					colorize(ColorGray, formatDuration(time.Since(participantStart))))
			}
			state.WithdrawalResults[participantID] = false
			continue
		}

		// Use the CreateTx output note for withdrawal proof to match cm_out exactly
		outNote := withdraw.Note{
			Coins:  outputTx.NewNote.Value.Coins,
			Energy: outputTx.NewNote.Value.Energy,
			Pk:     new(big.Int).SetBytes(outputTx.NewNote.PkOwner),
			Rho:    new(big.Int).SetBytes(outputTx.NewNote.Rho),
			R:      new(big.Int).SetBytes(outputTx.NewNote.Rand),
			Cm:     new(big.Int).SetBytes(outputTx.NewNote.Cm),
		}

		// Create auctioneer public key in correct format
		pkT := sw_bls12377.G1Affine{
			X: state.AuctioneerDHKp.Pk.X.String(),
			Y: state.AuctioneerDHKp.Pk.Y.String(),
		}

		// Use the same ciphertext from registration (first 5 fields only for withdraw compatibility)
		cipherAux := [5]*big.Int{
			state.ParticipantCAux[participantID][0],
			state.ParticipantCAux[participantID][1],
			state.ParticipantCAux[participantID][2],
			state.ParticipantCAux[participantID][3],
			state.ParticipantCAux[participantID][4],
		}

		// Execute withdrawal
		sharedSecretGnark := sw_bls12377.G1Affine{
			X: state.SharedSecrets[participantID].X.String(),
			Y: state.SharedSecrets[participantID].Y.String(),
		}
		withdrawTx, withdrawProof, err := withdraw.Withdraw(
			inNote,
			skIn,
			outNote,
			pkT,
			cipherAux,
			state.OrderPrices[participantID],
			sharedSecretGnark,
			withdrawalKeys.pkWithdraw,
			withdrawalKeys.ccsWithdraw,
		)

		if err != nil {
			if !quiet {
				fmt.Printf("Participant %02d                                     %s %s\n",
					participantID+1,
					formatStatus("FAILED"),
					colorize(ColorGray, formatDuration(time.Since(participantStart))))
			}
			state.WithdrawalResults[participantID] = false
		} else {
			// Store withdrawal data for later ledger submission
			cipherAuxStr := make([]string, 5)
			for i := 0; i < 5; i++ {
				cipherAuxStr[i] = withdrawTx.CipherAux[i].String()
			}
			withdrawTxData := map[string]interface{}{
				"sn_in":  withdrawTx.SnIn.String(),
				"cm_out": withdrawTx.CmOut.String(),
				"pk_t": map[string]string{
					"x": pkT.X.(string),
					"y": pkT.Y.(string),
				},
				"cipher_aux": cipherAuxStr,
				"old_coin":   inNote.Coins.String(),
				"old_energy": inNote.Energy.String(),
				"new_coin":   outNote.Coins.String(),
				"new_energy": outNote.Energy.String(),
			}

			// Store for batch ledger verification
			if state.WithdrawalTxs == nil {
				state.WithdrawalTxs = make([]*zerocash.Tx, 0)
				state.WithdrawalProofs = make([][]byte, 0)
				state.WithdrawalData = make([]map[string]interface{}, 0)
				state.WithdrawalIDs = make([]int, 0)
			}

			state.WithdrawalTxs = append(state.WithdrawalTxs, outputTx)
			state.WithdrawalProofs = append(state.WithdrawalProofs, withdrawProof)
			state.WithdrawalData = append(state.WithdrawalData, withdrawTxData)
			state.WithdrawalIDs = append(state.WithdrawalIDs, participantID)

			if !quiet {
				fmt.Printf("Participant %02d                                     %s %s\n",
					participantID+1,
					formatStatus("SUCCESS"),
					colorize(ColorGray, formatDuration(time.Since(participantStart))))
			}
		}

		// Add separator line between participants (except for the last one)
		if !quiet && i < len(participantsToWithdraw)-1 {
			fmt.Printf("%s\n", colorize(ColorGray, "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"))
		}
	}

	// LEDGER VERIFICATION SECTION
	if !quiet && len(state.WithdrawalTxs) > 0 {
		fmt.Printf("\nLedger Verification\n")
		fmt.Printf("%s Withdrawal proofs: %s\n",
			colorize(ColorCyan, "▸"),
			formatStatus("VERIFYING"))
	}

	// Process ledger verification for all withdrawals
	successCount = 0
	verificationStart := time.Now()
	for i, participantID := range state.WithdrawalIDs {
		// First, submit the underlying Alg.1 transaction proof to the ledger
		if !quiet {
			fmt.Printf("\x1b[31m▪ TX %02d Verification\x1b[0m\n", participantID+1)
		}
		if err := state.Ledger.SubmitTransaction(state.WithdrawalTxs[i], &zerocash.Params{}, fmt.Sprintf("participant_%d", participantID)); err != nil {
			state.WithdrawalResults[participantID] = false
			continue
		}

		// Then submit the withdrawal proof to the ledger
		if !quiet {
			fmt.Printf("\x1b[31m▪ Withdrawal %02d Verification\x1b[0m\n", participantID+1)
		}
		err := state.Ledger.SubmitWithdraw(state.WithdrawalData[i], state.WithdrawalProofs[i], fmt.Sprintf("participant_%d", participantID))
		if err != nil {
			state.WithdrawalResults[participantID] = false
		} else {
			state.WithdrawalResults[participantID] = true
			successCount++
		}
	}

	if !quiet && len(state.WithdrawalTxs) > 0 {
		printTreeItem(false, "TX proofs", "VERIFIED", 0)
		printTreeItem(false, "Withdrawal proofs", "VERIFIED", 0)
		printTreeItem(true, "Ledger submission", "COMPLETED", time.Since(verificationStart))
		fmt.Printf("\nWithdrawal Summary → %s participants processed\n",
			colorize(ColorBold, fmt.Sprintf("%d/%d", successCount, len(participantsToWithdraw))))
	}
}

// Clean Output Functions
var quiet bool // Global variable for output control

func printProtocolHeader(participants int, buyerRatio float64, verbosity string) {
	fmt.Println(colorize(ColorBrightCyan, "╔══════════════════════════════════════════════════════════════════════════════════╗"))
	fmt.Println(colorize(ColorBrightCyan, "║") + colorize(ColorBold, "                    PRIVACY-PRESERVING ENERGY MARKET                              ") + colorize(ColorBrightCyan, "║"))
	fmt.Println(colorize(ColorBrightCyan, "╚══════════════════════════════════════════════════════════════════════════════════╝"))
	fmt.Println()
	fmt.Printf("%s Configuration    Participants: %s • Buyers: %s • Verbosity: %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, fmt.Sprintf("%d", participants)),
		colorize(ColorBold, fmt.Sprintf("%.1f%%", buyerRatio*100)),
		colorize(ColorBold, verbosity))
	fmt.Printf("%s Timestamp        %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, time.Now().UTC().Format(time.RFC3339)))
	fmt.Printf("%s Environment      %s • %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, "Linux"),
		colorize(ColorBold, runtime.Version()))
	fmt.Println()
}

func printError(category, message string) {
	fmt.Printf("%s %s [%s]: %s\n", colorize(ColorRed, "✗"), colorize(ColorBold, "ERROR"), category, message)
	os.Exit(1)
}

func printPhaseHeader(phaseNum int, phaseName string) {
	phaseTitle := fmt.Sprintf("PHASE %d", phaseNum)
	separatorLength := 80 - len(phaseTitle) - len(phaseName) - 3
	separator := strings.Repeat("━", separatorLength)

	fmt.Printf("\n%s %s %s %s\n\n",
		colorize(ColorBrightBlue+ColorBold, phaseTitle),
		colorize(ColorBlue, separator),
		colorize(ColorBrightBlue+ColorBold, phaseName),
		"")
}

func printStep(stepNum, totalSteps int, stepName string) {
	fmt.Printf("%s\n", colorize(ColorBrightMagenta, stepName))
}

func printSubStep(description, status string, duration time.Duration) {
	alignedDesc := fmt.Sprintf("%-50s", description)
	if duration > 0 {
		fmt.Printf("%s %s %s\n",
			alignedDesc,
			formatStatus(status),
			colorize(ColorGray, formatDuration(duration)))
	} else {
		fmt.Printf("%s %s\n", alignedDesc, formatStatus(status))
	}
}

func printTreeItem(isLast bool, description, status string, duration time.Duration) {
	var prefix string
	if isLast {
		prefix = "└─"
	} else {
		prefix = "├─"
	}

	alignedDesc := fmt.Sprintf("%-45s", description)
	if duration > 0 {
		fmt.Printf("%s %s %s %s\n",
			colorize(ColorGray, prefix),
			alignedDesc,
			formatStatus(status),
			colorize(ColorGray, formatDuration(duration)))
	} else {
		fmt.Printf("%s %s %s\n",
			colorize(ColorGray, prefix),
			alignedDesc,
			formatStatus(status))
	}
}

func printPhaseComplete(duration time.Duration) {
	phaseCompleteText := "PHASE COMPLETE"
	separatorLength := 80 - len(phaseCompleteText) - len(formatDuration(duration)) - 3
	separator := strings.Repeat("━", separatorLength)

	fmt.Printf("\n%s %s %s\n",
		colorize(ColorBrightGreen+ColorBold, phaseCompleteText),
		colorize(ColorGreen, separator),
		colorize(ColorBrightGreen+ColorBold, formatDuration(duration)))
}

func printParticipantBox(participantID int, status string, details []string) {
	participantTitle := fmt.Sprintf("Participant %02d", participantID)

	fmt.Printf("┌─ %s %s\n",
		colorize(ColorBold, participantTitle),
		strings.Repeat("─", 65-len(participantTitle)))

	if len(details) > 0 {
		for _, detail := range details {
			fmt.Printf("│  %s\n", detail)
		}
		fmt.Printf("│%s\n", strings.Repeat(" ", 67))
	}

	fmt.Printf("│  ▸ Status                                                   %s\n", formatStatus(status))
	fmt.Printf("└%s\n", strings.Repeat("─", 68))
}

func printParticipantOneline(participantID int, status string, duration time.Duration) {
	participantTitle := fmt.Sprintf("Participant %02d", participantID)
	alignedDesc := fmt.Sprintf("%-50s", participantTitle)
	if duration > 0 {
		fmt.Printf("%s %s %s\n",
			alignedDesc,
			formatStatus(status),
			colorize(ColorGray, formatDuration(duration)))
	} else {
		fmt.Printf("%s %s\n", alignedDesc, formatStatus(status))
	}
}

type PhaseTiming struct {
	Setup        time.Duration
	Registration time.Duration
	Exchange     time.Duration
	Finalization time.Duration
	Withdrawal   time.Duration
}

func printProtocolSummary(state *ProtocolState, totalTime time.Duration, phaseTiming *PhaseTiming) {
	fmt.Println()
	fmt.Println(colorize(ColorBrightCyan, "╔══════════════════════════════════════════════════════════════════════════════════╗"))
	fmt.Println(colorize(ColorBrightCyan, "║") + colorize(ColorBold, "                                EXECUTION SUMMARY                                 ") + colorize(ColorBrightCyan, "║"))
	fmt.Println(colorize(ColorBrightCyan, "╚══════════════════════════════════════════════════════════════════════════════════╝"))
	fmt.Println()

	fmt.Printf("%s Total Runtime                                                          %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, formatDuration(totalTime)))
	withdrawnCount := 0
	for _, result := range state.WithdrawalResults {
		if result {
			withdrawnCount++
		}
	}

	if state.WithdrawalAttempts > 0 {
		fmt.Printf("%s Participants                   %s registered • %s exchanged • %s withdrawn\n",
			colorize(ColorCyan, "▸"),
			colorize(ColorBold, fmt.Sprintf("%d/%d", countNonZero(state.RegistrationProofs), state.Config.NumParticipants)),
			colorize(ColorBold, fmt.Sprintf("%d/%d", boolToCount(len(state.ExchangeProof) > 0), 1)),
			colorize(ColorBold, fmt.Sprintf("%d/%d", withdrawnCount, state.WithdrawalAttempts)))
	} else {
		fmt.Printf("%s Participants                   %s registered • %s exchanged\n",
			colorize(ColorCyan, "▸"),
			colorize(ColorBold, fmt.Sprintf("%d/%d", countNonZero(state.RegistrationProofs), state.Config.NumParticipants)),
			colorize(ColorBold, fmt.Sprintf("%d/%d", boolToCount(len(state.ExchangeProof) > 0), 1)))
	}
	fmt.Printf("%s Protocol Phases                %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, "5/5 completed"))
	fmt.Printf("%s Data Outputs                   %s\n",
		colorize(ColorCyan, "▸"),
		colorize(ColorBold, "3 files generated"))
	fmt.Println()

	fmt.Printf("%s Performance Metrics\n", colorize(ColorCyan, "▸"))
	printTreeItem(false, "Setup Phase", "", phaseTiming.Setup)
	printTreeItem(false, "Registration Phase", "", phaseTiming.Registration)
	if phaseTiming.Exchange > 0 {
		printTreeItem(false, "Exchange Phase", "", phaseTiming.Exchange)
	} else {
		printTreeItem(false, "Exchange Phase", "SKIPPED", 0)
	}
	if phaseTiming.Finalization > 0 {
		printTreeItem(false, "Finalization Phase", "", phaseTiming.Finalization)
	} else {
		printTreeItem(false, "Finalization Phase", "SKIPPED", 0)
	}
	if phaseTiming.Withdrawal > 0 {
		printTreeItem(true, "Withdrawal Phase", "", phaseTiming.Withdrawal)
	} else {
		printTreeItem(true, "Withdrawal Phase", "SKIPPED", 0)
	}
	fmt.Println()

	fmt.Printf("%s Circuit Statistics\n", colorize(ColorCyan, "▸"))
	printTreeItem(false, "Transaction Circuit           10658 constraints • BW6-761 Groth16", "", 0)
	printTreeItem(false, "Registration Circuit           9679 constraints • BW6-761 Groth16", "", 0)
	printTreeItem(true, "Withdrawal Circuit             6364 constraints • BW6-761 Groth16", "", 0)
}

// Helper functions

// SimpleExchangeManager - Simple replacement for the complex CircuitKeyManager
type SimpleExchangeManager struct {
	pk  groth16.ProvingKey
	vk  groth16.VerifyingKey
	ccs constraint.ConstraintSystem
	n   int
}

func (s *SimpleExchangeManager) GetOrCreateCircuitKeys(n int) (*exchange.CircuitKeys, error) {
	if s.n != n {
		return nil, fmt.Errorf("circuit compiled for N=%d, but N=%d requested", s.n, n)
	}
	return &exchange.CircuitKeys{
		ProvingKey:       s.pk,
		VerifyingKey:     s.vk,
		ConstraintSystem: s.ccs,
		ParticipantCount: s.n,
	}, nil
}

func (s *SimpleExchangeManager) PrecompileCircuits(counts []int) error {
	// Not needed in simple version
	return nil
}

func setupCircuitKeys(participantCount int) (*CircuitKeys, error) {
	simpleCache := cache.NewSimpleCache(".ppem_cache/circuits")
	keys := &CircuitKeys{}
	var err error

	// TX Circuit
	if pk, vk, ccs, found := simpleCache.Load("tx"); found {
		if !quiet {
			printTreeItem(false, "Transaction circuit", "CACHED", 0)
		}
		keys.pkTx, keys.vkTx, keys.ccsTx = pk, vk, ccs
	} else {
		compileStart := time.Now()
		var circuit zerocash.CircuitTx
		keys.ccsTx, err = frontend.Compile(ecc.BW6_761.ScalarField(), r1cs.NewBuilder, &circuit)
		if err != nil {
			return nil, err
		}
		keys.pkTx, keys.vkTx, err = groth16.Setup(keys.ccsTx)
		if err != nil {
			return nil, err
		}
		simpleCache.Save("tx", keys.pkTx, keys.vkTx, keys.ccsTx)
		if !quiet {
			printTreeItem(false, "Transaction circuit", "COMPILED", time.Since(compileStart))
		}
	}

	// Registration Circuit
	if pk, vk, ccs, found := simpleCache.Load("reg"); found {
		if !quiet {
			printTreeItem(false, "Registration circuit", "CACHED", 0)
		}
		keys.pkReg, keys.vkReg, keys.ccsReg = pk, vk, ccs
	} else {
		compileStart := time.Now()
		var circuit register.CircuitTxRegister
		keys.ccsReg, err = frontend.Compile(ecc.BW6_761.ScalarField(), r1cs.NewBuilder, &circuit)
		if err != nil {
			return nil, err
		}
		keys.pkReg, keys.vkReg, err = groth16.Setup(keys.ccsReg)
		if err != nil {
			return nil, err
		}
		simpleCache.Save("reg", keys.pkReg, keys.vkReg, keys.ccsReg)
		if !quiet {
			printTreeItem(false, "Registration circuit", "COMPILED", time.Since(compileStart))
		}
	}

	// Exchange Circuit (dynamic for N participants)
	exchangeName := fmt.Sprintf("exchange_N%d", participantCount)
	if pk, vk, ccs, found := simpleCache.Load(exchangeName); found {
		if !quiet {
			printTreeItem(true, fmt.Sprintf("Exchange circuit [N=%d]", participantCount), "CACHED", 0)
		}
		keys.DynamicManager = &SimpleExchangeManager{
			pk:  pk,
			vk:  vk,
			ccs: ccs,
			n:   participantCount,
		}
	} else {
		compileStart := time.Now()
		circuit := exchange.NewCircuitTxFN(participantCount)
		ccs, err := frontend.Compile(ecc.BW6_761.ScalarField(), r1cs.NewBuilder, circuit)
		if err != nil {
			return nil, fmt.Errorf("exchange circuit compilation failed: %w", err)
		}
		pk, vk, err := groth16.Setup(ccs)
		if err != nil {
			return nil, fmt.Errorf("exchange circuit setup failed: %w", err)
		}
		simpleCache.Save(exchangeName, pk, vk, ccs)
		if !quiet {
			printTreeItem(true, fmt.Sprintf("Exchange circuit [N=%d]", participantCount), "COMPILED", time.Since(compileStart))
		}

		keys.DynamicManager = &SimpleExchangeManager{
			pk:  pk,
			vk:  vk,
			ccs: ccs,
			n:   participantCount,
		}
	}

	return keys, nil
}

func setupWithdrawalKeys() (*CircuitKeys, error) {
	simpleCache := cache.NewSimpleCache(".ppem_cache/circuits")
	keys := &CircuitKeys{}
	var err error

	// Withdraw Circuit
	if pk, vk, ccs, found := simpleCache.Load("withdraw"); found {
		keys.pkWithdraw, keys.vkWithdraw, keys.ccsWithdraw = pk, vk, ccs
		return keys, nil
	}

	var circuit withdraw.CircuitWithdraw
	keys.ccsWithdraw, err = frontend.Compile(ecc.BW6_761.ScalarField(), r1cs.NewBuilder, &circuit)
	if err != nil {
		return nil, err
	}
	keys.pkWithdraw, keys.vkWithdraw, err = groth16.Setup(keys.ccsWithdraw)
	if err != nil {
		return nil, err
	}
	simpleCache.Save("withdraw", keys.pkWithdraw, keys.vkWithdraw, keys.ccsWithdraw)

	return keys, nil
}

// computeMimcCommitment computes a MiMC-based commitment
func computeMimcCommitment(coins, energy, pk, rho, rand *big.Int) *big.Int {
	h := zerocash.NewMiMC()
	h.Write(coins.Bytes())
	h.Write(energy.Bytes())
	h.Write(pk.Bytes())
	h.Write(rho.Bytes())
	h.Write(rand.Bytes())
	return new(big.Int).SetBytes(h.Sum(nil))
}

// printProtocolSummary prints a summary of the protocol execution
// printProtocolSummary is now defined in the clean output functions above

func countNonZero(arr [][]byte) int {
	c := 0
	for _, b := range arr {
		if len(b) > 0 {
			c++
		}
	}
	return c
}
func boolToCount(b bool) int {
	if b {
		return 1
	}
	return 0
}

// getBuyerRatio calculates the fraction of participants that are buyers
func getBuyerRatio(roles map[int]zerocash.OrderType) float64 {
	if len(roles) == 0 {
		return 0.0
	}

	buyers := 0
	for _, role := range roles {
		if role == zerocash.BUY {
			buyers++
		}
	}

	return float64(buyers) / float64(len(roles))
}

// countBuyers counts the number of buyers in the roles map
func countBuyers(roles map[int]zerocash.OrderType) int {
	buyers := 0
	for _, role := range roles {
		if role == zerocash.BUY {
			buyers++
		}
	}
	return buyers
}

// countSellers counts the number of sellers in the roles map
func countSellers(roles map[int]zerocash.OrderType) int {
	sellers := 0
	for _, role := range roles {
		if role == zerocash.SELL {
			sellers++
		}
	}
	return sellers
}
